[2017-03-14 19:48:30,111] INFO Starting the log cleaner (kafka.log.LogCleaner)
[2017-03-14 19:48:30,113] INFO [kafka-log-cleaner-thread-0], Starting  (kafka.log.LogCleaner)
[2017-03-21 09:04:20,184] INFO Starting the log cleaner (kafka.log.LogCleaner)
[2017-03-21 09:04:20,187] INFO [kafka-log-cleaner-thread-0], Starting  (kafka.log.LogCleaner)
[2017-03-23 20:15:15,770] INFO Starting the log cleaner (kafka.log.LogCleaner)
[2017-03-23 20:15:15,773] INFO [kafka-log-cleaner-thread-0], Starting  (kafka.log.LogCleaner)
[2017-03-23 20:15:45,812] INFO Cleaner 0: Beginning cleaning of log __consumer_offsets-10. (kafka.log.LogCleaner)
[2017-03-23 20:15:45,814] INFO Cleaner 0: Building offset map for __consumer_offsets-10... (kafka.log.LogCleaner)
[2017-03-23 20:15:45,861] INFO Cleaner 0: Building offset map for log __consumer_offsets-10 for 1 segments in offset range [0, 6). (kafka.log.LogCleaner)
[2017-03-23 20:15:45,864] INFO Cleaner 0: Offset map for log __consumer_offsets-10 complete. (kafka.log.LogCleaner)
[2017-03-23 20:15:45,871] INFO Cleaner 0: Cleaning log __consumer_offsets-10 (cleaning prior to Tue Mar 21 09:06:24 CET 2017, discarding tombstones prior to Thu Jan 01 01:00:00 CET 1970)... (kafka.log.LogCleaner)
[2017-03-23 20:15:45,874] INFO Cleaner 0: Cleaning segment 0 in log __consumer_offsets-10 (largest timestamp Tue Mar 21 09:06:22 CET 2017) into 0, retaining deletes. (kafka.log.LogCleaner)
[2017-03-23 20:15:45,893] INFO Cleaner 0: Swapping in cleaned segment 0 for segment(s) 0 in log __consumer_offsets-10. (kafka.log.LogCleaner)
[2017-03-23 20:15:45,905] ERROR [kafka-log-cleaner-thread-0], Error due to  (kafka.log.LogCleaner)
kafka.common.KafkaStorageException: Failed to change the log file suffix from .cleaned to .swap for log segment 0
	at kafka.log.LogSegment.kafkaStorageException$1(LogSegment.scala:340)
	at kafka.log.LogSegment.changeFileSuffixes(LogSegment.scala:342)
	at kafka.log.Log.replaceSegments(Log.scala:1018)
	at kafka.log.Cleaner.cleanSegments(LogCleaner.scala:426)
	at kafka.log.Cleaner$$anonfun$clean$4.apply(LogCleaner.scala:363)
	at kafka.log.Cleaner$$anonfun$clean$4.apply(LogCleaner.scala:362)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at kafka.log.Cleaner.clean(LogCleaner.scala:362)
	at kafka.log.LogCleaner$CleanerThread.cleanOrSleep(LogCleaner.scala:241)
	at kafka.log.LogCleaner$CleanerThread.doWork(LogCleaner.scala:220)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:63)
Caused by: java.nio.file.FileSystemException: \tmp\kafka-logs\__consumer_offsets-10\00000000000000000000.log.cleaned -> \tmp\kafka-logs\__consumer_offsets-10\00000000000000000000.log.swap: El proceso no tiene acceso al archivo porque está siendo utilizado por otro proceso.

	at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:86)
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
	at sun.nio.fs.WindowsFileCopy.move(WindowsFileCopy.java:387)
	at sun.nio.fs.WindowsFileSystemProvider.move(WindowsFileSystemProvider.java:287)
	at java.nio.file.Files.move(Files.java:1395)
	at org.apache.kafka.common.utils.Utils.atomicMoveWithFallback(Utils.java:711)
	at org.apache.kafka.common.record.FileRecords.renameTo(FileRecords.java:210)
	... 10 more
	Suppressed: java.nio.file.FileSystemException: \tmp\kafka-logs\__consumer_offsets-10\00000000000000000000.log.cleaned -> \tmp\kafka-logs\__consumer_offsets-10\00000000000000000000.log.swap: El proceso no tiene acceso al archivo porque está siendo utilizado por otro proceso.

		at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:86)
		at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
		at sun.nio.fs.WindowsFileCopy.move(WindowsFileCopy.java:301)
		at sun.nio.fs.WindowsFileSystemProvider.move(WindowsFileSystemProvider.java:287)
		at java.nio.file.Files.move(Files.java:1395)
		at org.apache.kafka.common.utils.Utils.atomicMoveWithFallback(Utils.java:708)
		... 11 more
[2017-03-23 20:15:45,906] INFO [kafka-log-cleaner-thread-0], Stopped  (kafka.log.LogCleaner)
[2017-03-23 20:30:46,990] INFO Shutting down the log cleaner. (kafka.log.LogCleaner)
[2017-03-23 20:30:46,991] INFO [kafka-log-cleaner-thread-0], Shutting down (kafka.log.LogCleaner)
[2017-03-23 20:30:46,991] INFO [kafka-log-cleaner-thread-0], Shutdown completed (kafka.log.LogCleaner)
[2017-03-23 20:31:10,966] INFO Starting the log cleaner (kafka.log.LogCleaner)
[2017-03-23 20:31:10,968] INFO [kafka-log-cleaner-thread-0], Starting  (kafka.log.LogCleaner)
[2017-03-23 20:31:10,992] INFO Cleaner 0: Beginning cleaning of log __consumer_offsets-10. (kafka.log.LogCleaner)
[2017-03-23 20:31:10,992] INFO Cleaner 0: Building offset map for __consumer_offsets-10... (kafka.log.LogCleaner)
[2017-03-23 20:31:11,035] INFO Cleaner 0: Building offset map for log __consumer_offsets-10 for 1 segments in offset range [0, 6). (kafka.log.LogCleaner)
[2017-03-23 20:31:11,044] INFO Cleaner 0: Offset map for log __consumer_offsets-10 complete. (kafka.log.LogCleaner)
[2017-03-23 20:31:11,052] INFO Cleaner 0: Cleaning log __consumer_offsets-10 (cleaning prior to Tue Mar 21 09:06:24 CET 2017, discarding tombstones prior to Thu Jan 01 01:00:00 CET 1970)... (kafka.log.LogCleaner)
[2017-03-23 20:31:11,057] INFO Cleaner 0: Cleaning segment 0 in log __consumer_offsets-10 (largest timestamp Tue Mar 21 09:06:22 CET 2017) into 0, retaining deletes. (kafka.log.LogCleaner)
[2017-03-23 20:31:11,101] INFO Cleaner 0: Swapping in cleaned segment 0 for segment(s) 0 in log __consumer_offsets-10. (kafka.log.LogCleaner)
[2017-03-23 20:31:11,115] ERROR [kafka-log-cleaner-thread-0], Error due to  (kafka.log.LogCleaner)
kafka.common.KafkaStorageException: Failed to change the log file suffix from .cleaned to .swap for log segment 0
	at kafka.log.LogSegment.kafkaStorageException$1(LogSegment.scala:340)
	at kafka.log.LogSegment.changeFileSuffixes(LogSegment.scala:342)
	at kafka.log.Log.replaceSegments(Log.scala:1018)
	at kafka.log.Cleaner.cleanSegments(LogCleaner.scala:426)
	at kafka.log.Cleaner$$anonfun$clean$4.apply(LogCleaner.scala:363)
	at kafka.log.Cleaner$$anonfun$clean$4.apply(LogCleaner.scala:362)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at kafka.log.Cleaner.clean(LogCleaner.scala:362)
	at kafka.log.LogCleaner$CleanerThread.cleanOrSleep(LogCleaner.scala:241)
	at kafka.log.LogCleaner$CleanerThread.doWork(LogCleaner.scala:220)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:63)
Caused by: java.nio.file.FileSystemException: \tmp\kafka-logs\__consumer_offsets-10\00000000000000000000.log.cleaned -> \tmp\kafka-logs\__consumer_offsets-10\00000000000000000000.log.swap: El proceso no tiene acceso al archivo porque está siendo utilizado por otro proceso.

	at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:86)
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
	at sun.nio.fs.WindowsFileCopy.move(WindowsFileCopy.java:387)
	at sun.nio.fs.WindowsFileSystemProvider.move(WindowsFileSystemProvider.java:287)
	at java.nio.file.Files.move(Files.java:1395)
	at org.apache.kafka.common.utils.Utils.atomicMoveWithFallback(Utils.java:711)
	at org.apache.kafka.common.record.FileRecords.renameTo(FileRecords.java:210)
	... 10 more
	Suppressed: java.nio.file.FileSystemException: \tmp\kafka-logs\__consumer_offsets-10\00000000000000000000.log.cleaned -> \tmp\kafka-logs\__consumer_offsets-10\00000000000000000000.log.swap: El proceso no tiene acceso al archivo porque está siendo utilizado por otro proceso.

		at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:86)
		at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
		at sun.nio.fs.WindowsFileCopy.move(WindowsFileCopy.java:301)
		at sun.nio.fs.WindowsFileSystemProvider.move(WindowsFileSystemProvider.java:287)
		at java.nio.file.Files.move(Files.java:1395)
		at org.apache.kafka.common.utils.Utils.atomicMoveWithFallback(Utils.java:708)
		... 11 more
[2017-03-23 20:31:11,120] INFO [kafka-log-cleaner-thread-0], Stopped  (kafka.log.LogCleaner)
[2017-03-26 14:25:22,115] INFO Starting the log cleaner (kafka.log.LogCleaner)
[2017-03-26 14:25:22,119] INFO [kafka-log-cleaner-thread-0], Starting  (kafka.log.LogCleaner)
[2017-03-26 14:25:22,154] INFO Cleaner 0: Beginning cleaning of log __consumer_offsets-7. (kafka.log.LogCleaner)
[2017-03-26 14:25:22,155] INFO Cleaner 0: Building offset map for __consumer_offsets-7... (kafka.log.LogCleaner)
[2017-03-26 14:25:22,200] INFO Cleaner 0: Building offset map for log __consumer_offsets-7 for 1 segments in offset range [0, 5). (kafka.log.LogCleaner)
[2017-03-26 14:25:22,213] INFO Cleaner 0: Offset map for log __consumer_offsets-7 complete. (kafka.log.LogCleaner)
[2017-03-26 14:25:22,220] INFO Cleaner 0: Cleaning log __consumer_offsets-7 (cleaning prior to Tue Mar 21 09:14:25 CET 2017, discarding tombstones prior to Thu Jan 01 01:00:00 CET 1970)... (kafka.log.LogCleaner)
[2017-03-26 14:25:22,227] INFO Cleaner 0: Cleaning segment 0 in log __consumer_offsets-7 (largest timestamp Tue Mar 21 09:14:21 CET 2017) into 0, retaining deletes. (kafka.log.LogCleaner)
[2017-03-26 14:25:22,280] INFO Cleaner 0: Swapping in cleaned segment 0 for segment(s) 0 in log __consumer_offsets-7. (kafka.log.LogCleaner)
[2017-03-26 14:25:22,300] ERROR [kafka-log-cleaner-thread-0], Error due to  (kafka.log.LogCleaner)
kafka.common.KafkaStorageException: Failed to change the log file suffix from .cleaned to .swap for log segment 0
	at kafka.log.LogSegment.kafkaStorageException$1(LogSegment.scala:340)
	at kafka.log.LogSegment.changeFileSuffixes(LogSegment.scala:342)
	at kafka.log.Log.replaceSegments(Log.scala:1018)
	at kafka.log.Cleaner.cleanSegments(LogCleaner.scala:426)
	at kafka.log.Cleaner$$anonfun$clean$4.apply(LogCleaner.scala:363)
	at kafka.log.Cleaner$$anonfun$clean$4.apply(LogCleaner.scala:362)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at kafka.log.Cleaner.clean(LogCleaner.scala:362)
	at kafka.log.LogCleaner$CleanerThread.cleanOrSleep(LogCleaner.scala:241)
	at kafka.log.LogCleaner$CleanerThread.doWork(LogCleaner.scala:220)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:63)
Caused by: java.nio.file.FileSystemException: \tmp\kafka-logs\__consumer_offsets-7\00000000000000000000.log.cleaned -> \tmp\kafka-logs\__consumer_offsets-7\00000000000000000000.log.swap: El proceso no tiene acceso al archivo porque está siendo utilizado por otro proceso.

	at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:86)
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
	at sun.nio.fs.WindowsFileCopy.move(WindowsFileCopy.java:387)
	at sun.nio.fs.WindowsFileSystemProvider.move(WindowsFileSystemProvider.java:287)
	at java.nio.file.Files.move(Files.java:1395)
	at org.apache.kafka.common.utils.Utils.atomicMoveWithFallback(Utils.java:711)
	at org.apache.kafka.common.record.FileRecords.renameTo(FileRecords.java:210)
	... 10 more
	Suppressed: java.nio.file.FileSystemException: \tmp\kafka-logs\__consumer_offsets-7\00000000000000000000.log.cleaned -> \tmp\kafka-logs\__consumer_offsets-7\00000000000000000000.log.swap: El proceso no tiene acceso al archivo porque está siendo utilizado por otro proceso.

		at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:86)
		at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
		at sun.nio.fs.WindowsFileCopy.move(WindowsFileCopy.java:301)
		at sun.nio.fs.WindowsFileSystemProvider.move(WindowsFileSystemProvider.java:287)
		at java.nio.file.Files.move(Files.java:1395)
		at org.apache.kafka.common.utils.Utils.atomicMoveWithFallback(Utils.java:708)
		... 11 more
[2017-03-26 14:25:22,304] INFO [kafka-log-cleaner-thread-0], Stopped  (kafka.log.LogCleaner)
[2017-03-27 21:20:44,887] INFO Starting the log cleaner (kafka.log.LogCleaner)
[2017-03-27 21:20:44,904] INFO [kafka-log-cleaner-thread-0], Starting  (kafka.log.LogCleaner)
[2017-03-27 21:20:44,962] INFO Cleaner 0: Beginning cleaning of log __consumer_offsets-7. (kafka.log.LogCleaner)
[2017-03-27 21:20:44,965] INFO Cleaner 0: Building offset map for __consumer_offsets-7... (kafka.log.LogCleaner)
[2017-03-27 21:20:45,014] INFO Cleaner 0: Building offset map for log __consumer_offsets-7 for 1 segments in offset range [0, 5). (kafka.log.LogCleaner)
[2017-03-27 21:20:45,028] INFO Cleaner 0: Offset map for log __consumer_offsets-7 complete. (kafka.log.LogCleaner)
[2017-03-27 21:20:45,038] INFO Cleaner 0: Cleaning log __consumer_offsets-7 (cleaning prior to Tue Mar 21 09:14:25 CET 2017, discarding tombstones prior to Thu Jan 01 01:00:00 CET 1970)... (kafka.log.LogCleaner)
[2017-03-27 21:20:45,045] INFO Cleaner 0: Cleaning segment 0 in log __consumer_offsets-7 (largest timestamp Tue Mar 21 09:14:21 CET 2017) into 0, retaining deletes. (kafka.log.LogCleaner)
[2017-03-27 21:20:45,117] INFO Cleaner 0: Swapping in cleaned segment 0 for segment(s) 0 in log __consumer_offsets-7. (kafka.log.LogCleaner)
[2017-03-27 21:20:45,137] ERROR [kafka-log-cleaner-thread-0], Error due to  (kafka.log.LogCleaner)
kafka.common.KafkaStorageException: Failed to change the log file suffix from .cleaned to .swap for log segment 0
	at kafka.log.LogSegment.kafkaStorageException$1(LogSegment.scala:340)
	at kafka.log.LogSegment.changeFileSuffixes(LogSegment.scala:342)
	at kafka.log.Log.replaceSegments(Log.scala:1018)
	at kafka.log.Cleaner.cleanSegments(LogCleaner.scala:426)
	at kafka.log.Cleaner$$anonfun$clean$4.apply(LogCleaner.scala:363)
	at kafka.log.Cleaner$$anonfun$clean$4.apply(LogCleaner.scala:362)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at kafka.log.Cleaner.clean(LogCleaner.scala:362)
	at kafka.log.LogCleaner$CleanerThread.cleanOrSleep(LogCleaner.scala:241)
	at kafka.log.LogCleaner$CleanerThread.doWork(LogCleaner.scala:220)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:63)
Caused by: java.nio.file.FileSystemException: \tmp\kafka-logs\__consumer_offsets-7\00000000000000000000.log.cleaned -> \tmp\kafka-logs\__consumer_offsets-7\00000000000000000000.log.swap: El proceso no tiene acceso al archivo porque está siendo utilizado por otro proceso.

	at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:86)
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
	at sun.nio.fs.WindowsFileCopy.move(WindowsFileCopy.java:387)
	at sun.nio.fs.WindowsFileSystemProvider.move(WindowsFileSystemProvider.java:287)
	at java.nio.file.Files.move(Files.java:1395)
	at org.apache.kafka.common.utils.Utils.atomicMoveWithFallback(Utils.java:711)
	at org.apache.kafka.common.record.FileRecords.renameTo(FileRecords.java:210)
	... 10 more
	Suppressed: java.nio.file.FileSystemException: \tmp\kafka-logs\__consumer_offsets-7\00000000000000000000.log.cleaned -> \tmp\kafka-logs\__consumer_offsets-7\00000000000000000000.log.swap: El proceso no tiene acceso al archivo porque está siendo utilizado por otro proceso.

		at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:86)
		at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
		at sun.nio.fs.WindowsFileCopy.move(WindowsFileCopy.java:301)
		at sun.nio.fs.WindowsFileSystemProvider.move(WindowsFileSystemProvider.java:287)
		at java.nio.file.Files.move(Files.java:1395)
		at org.apache.kafka.common.utils.Utils.atomicMoveWithFallback(Utils.java:708)
		... 11 more
[2017-03-27 21:20:45,147] INFO [kafka-log-cleaner-thread-0], Stopped  (kafka.log.LogCleaner)
[2017-03-28 09:05:16,793] INFO Starting the log cleaner (kafka.log.LogCleaner)
[2017-03-28 09:05:16,796] INFO [kafka-log-cleaner-thread-0], Starting  (kafka.log.LogCleaner)
[2017-03-28 09:05:16,826] INFO Cleaner 0: Beginning cleaning of log __consumer_offsets-7. (kafka.log.LogCleaner)
[2017-03-28 09:05:16,827] INFO Cleaner 0: Building offset map for __consumer_offsets-7... (kafka.log.LogCleaner)
[2017-03-28 09:05:16,871] INFO Cleaner 0: Building offset map for log __consumer_offsets-7 for 1 segments in offset range [0, 5). (kafka.log.LogCleaner)
[2017-03-28 09:05:16,880] INFO Cleaner 0: Offset map for log __consumer_offsets-7 complete. (kafka.log.LogCleaner)
[2017-03-28 09:05:16,887] INFO Cleaner 0: Cleaning log __consumer_offsets-7 (cleaning prior to Tue Mar 21 09:14:25 CET 2017, discarding tombstones prior to Thu Jan 01 01:00:00 CET 1970)... (kafka.log.LogCleaner)
[2017-03-28 09:05:16,892] INFO Cleaner 0: Cleaning segment 0 in log __consumer_offsets-7 (largest timestamp Tue Mar 21 09:14:21 CET 2017) into 0, retaining deletes. (kafka.log.LogCleaner)
[2017-03-28 09:05:16,934] INFO Cleaner 0: Swapping in cleaned segment 0 for segment(s) 0 in log __consumer_offsets-7. (kafka.log.LogCleaner)
[2017-03-28 09:05:16,951] ERROR [kafka-log-cleaner-thread-0], Error due to  (kafka.log.LogCleaner)
kafka.common.KafkaStorageException: Failed to change the log file suffix from .cleaned to .swap for log segment 0
	at kafka.log.LogSegment.kafkaStorageException$1(LogSegment.scala:340)
	at kafka.log.LogSegment.changeFileSuffixes(LogSegment.scala:342)
	at kafka.log.Log.replaceSegments(Log.scala:1018)
	at kafka.log.Cleaner.cleanSegments(LogCleaner.scala:426)
	at kafka.log.Cleaner$$anonfun$clean$4.apply(LogCleaner.scala:363)
	at kafka.log.Cleaner$$anonfun$clean$4.apply(LogCleaner.scala:362)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at kafka.log.Cleaner.clean(LogCleaner.scala:362)
	at kafka.log.LogCleaner$CleanerThread.cleanOrSleep(LogCleaner.scala:241)
	at kafka.log.LogCleaner$CleanerThread.doWork(LogCleaner.scala:220)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:63)
Caused by: java.nio.file.FileSystemException: \tmp\kafka-logs\__consumer_offsets-7\00000000000000000000.log.cleaned -> \tmp\kafka-logs\__consumer_offsets-7\00000000000000000000.log.swap: El proceso no tiene acceso al archivo porque está siendo utilizado por otro proceso.

	at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:86)
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
	at sun.nio.fs.WindowsFileCopy.move(WindowsFileCopy.java:387)
	at sun.nio.fs.WindowsFileSystemProvider.move(WindowsFileSystemProvider.java:287)
	at java.nio.file.Files.move(Files.java:1395)
	at org.apache.kafka.common.utils.Utils.atomicMoveWithFallback(Utils.java:711)
	at org.apache.kafka.common.record.FileRecords.renameTo(FileRecords.java:210)
	... 10 more
	Suppressed: java.nio.file.FileSystemException: \tmp\kafka-logs\__consumer_offsets-7\00000000000000000000.log.cleaned -> \tmp\kafka-logs\__consumer_offsets-7\00000000000000000000.log.swap: El proceso no tiene acceso al archivo porque está siendo utilizado por otro proceso.

		at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:86)
		at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
		at sun.nio.fs.WindowsFileCopy.move(WindowsFileCopy.java:301)
		at sun.nio.fs.WindowsFileSystemProvider.move(WindowsFileSystemProvider.java:287)
		at java.nio.file.Files.move(Files.java:1395)
		at org.apache.kafka.common.utils.Utils.atomicMoveWithFallback(Utils.java:708)
		... 11 more
[2017-03-28 09:05:16,955] INFO [kafka-log-cleaner-thread-0], Stopped  (kafka.log.LogCleaner)
[2017-03-28 16:42:59,163] INFO Starting the log cleaner (kafka.log.LogCleaner)
[2017-03-28 16:42:59,171] INFO [kafka-log-cleaner-thread-0], Starting  (kafka.log.LogCleaner)
[2017-03-28 16:42:59,240] INFO Cleaner 0: Beginning cleaning of log __consumer_offsets-7. (kafka.log.LogCleaner)
[2017-03-28 16:42:59,241] INFO Cleaner 0: Building offset map for __consumer_offsets-7... (kafka.log.LogCleaner)
[2017-03-28 16:42:59,288] INFO Cleaner 0: Building offset map for log __consumer_offsets-7 for 1 segments in offset range [0, 5). (kafka.log.LogCleaner)
[2017-03-28 16:42:59,307] INFO Cleaner 0: Offset map for log __consumer_offsets-7 complete. (kafka.log.LogCleaner)
[2017-03-28 16:42:59,316] INFO Cleaner 0: Cleaning log __consumer_offsets-7 (cleaning prior to Tue Mar 21 09:14:25 CET 2017, discarding tombstones prior to Thu Jan 01 01:00:00 CET 1970)... (kafka.log.LogCleaner)
[2017-03-28 16:42:59,322] INFO Cleaner 0: Cleaning segment 0 in log __consumer_offsets-7 (largest timestamp Tue Mar 21 09:14:21 CET 2017) into 0, retaining deletes. (kafka.log.LogCleaner)
[2017-03-28 16:42:59,433] INFO Cleaner 0: Swapping in cleaned segment 0 for segment(s) 0 in log __consumer_offsets-7. (kafka.log.LogCleaner)
[2017-03-28 16:42:59,461] ERROR [kafka-log-cleaner-thread-0], Error due to  (kafka.log.LogCleaner)
kafka.common.KafkaStorageException: Failed to change the log file suffix from .cleaned to .swap for log segment 0
	at kafka.log.LogSegment.kafkaStorageException$1(LogSegment.scala:340)
	at kafka.log.LogSegment.changeFileSuffixes(LogSegment.scala:342)
	at kafka.log.Log.replaceSegments(Log.scala:1018)
	at kafka.log.Cleaner.cleanSegments(LogCleaner.scala:426)
	at kafka.log.Cleaner$$anonfun$clean$4.apply(LogCleaner.scala:363)
	at kafka.log.Cleaner$$anonfun$clean$4.apply(LogCleaner.scala:362)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at kafka.log.Cleaner.clean(LogCleaner.scala:362)
	at kafka.log.LogCleaner$CleanerThread.cleanOrSleep(LogCleaner.scala:241)
	at kafka.log.LogCleaner$CleanerThread.doWork(LogCleaner.scala:220)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:63)
Caused by: java.nio.file.FileSystemException: \tmp\kafka-logs\__consumer_offsets-7\00000000000000000000.log.cleaned -> \tmp\kafka-logs\__consumer_offsets-7\00000000000000000000.log.swap: El proceso no tiene acceso al archivo porque está siendo utilizado por otro proceso.

	at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:86)
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
	at sun.nio.fs.WindowsFileCopy.move(WindowsFileCopy.java:387)
	at sun.nio.fs.WindowsFileSystemProvider.move(WindowsFileSystemProvider.java:287)
	at java.nio.file.Files.move(Files.java:1395)
	at org.apache.kafka.common.utils.Utils.atomicMoveWithFallback(Utils.java:711)
	at org.apache.kafka.common.record.FileRecords.renameTo(FileRecords.java:210)
	... 10 more
	Suppressed: java.nio.file.FileSystemException: \tmp\kafka-logs\__consumer_offsets-7\00000000000000000000.log.cleaned -> \tmp\kafka-logs\__consumer_offsets-7\00000000000000000000.log.swap: El proceso no tiene acceso al archivo porque está siendo utilizado por otro proceso.

		at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:86)
		at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
		at sun.nio.fs.WindowsFileCopy.move(WindowsFileCopy.java:301)
		at sun.nio.fs.WindowsFileSystemProvider.move(WindowsFileSystemProvider.java:287)
		at java.nio.file.Files.move(Files.java:1395)
		at org.apache.kafka.common.utils.Utils.atomicMoveWithFallback(Utils.java:708)
		... 11 more
[2017-03-28 16:42:59,487] INFO [kafka-log-cleaner-thread-0], Stopped  (kafka.log.LogCleaner)
[2017-03-28 20:09:46,007] INFO Starting the log cleaner (kafka.log.LogCleaner)
[2017-03-28 20:09:46,010] INFO [kafka-log-cleaner-thread-0], Starting  (kafka.log.LogCleaner)
[2017-03-28 20:09:46,033] INFO Cleaner 0: Beginning cleaning of log __consumer_offsets-7. (kafka.log.LogCleaner)
[2017-03-28 20:09:46,033] INFO Cleaner 0: Building offset map for __consumer_offsets-7... (kafka.log.LogCleaner)
[2017-03-28 20:09:46,073] INFO Cleaner 0: Building offset map for log __consumer_offsets-7 for 1 segments in offset range [0, 5). (kafka.log.LogCleaner)
[2017-03-28 20:09:46,081] INFO Cleaner 0: Offset map for log __consumer_offsets-7 complete. (kafka.log.LogCleaner)
[2017-03-28 20:09:46,086] INFO Cleaner 0: Cleaning log __consumer_offsets-7 (cleaning prior to Tue Mar 21 09:14:25 CET 2017, discarding tombstones prior to Thu Jan 01 01:00:00 CET 1970)... (kafka.log.LogCleaner)
[2017-03-28 20:09:46,090] INFO Cleaner 0: Cleaning segment 0 in log __consumer_offsets-7 (largest timestamp Tue Mar 21 09:14:21 CET 2017) into 0, retaining deletes. (kafka.log.LogCleaner)
[2017-03-28 20:09:46,137] INFO Cleaner 0: Swapping in cleaned segment 0 for segment(s) 0 in log __consumer_offsets-7. (kafka.log.LogCleaner)
[2017-03-28 20:09:46,157] ERROR [kafka-log-cleaner-thread-0], Error due to  (kafka.log.LogCleaner)
kafka.common.KafkaStorageException: Failed to change the log file suffix from .cleaned to .swap for log segment 0
	at kafka.log.LogSegment.kafkaStorageException$1(LogSegment.scala:340)
	at kafka.log.LogSegment.changeFileSuffixes(LogSegment.scala:342)
	at kafka.log.Log.replaceSegments(Log.scala:1018)
	at kafka.log.Cleaner.cleanSegments(LogCleaner.scala:426)
	at kafka.log.Cleaner$$anonfun$clean$4.apply(LogCleaner.scala:363)
	at kafka.log.Cleaner$$anonfun$clean$4.apply(LogCleaner.scala:362)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at kafka.log.Cleaner.clean(LogCleaner.scala:362)
	at kafka.log.LogCleaner$CleanerThread.cleanOrSleep(LogCleaner.scala:241)
	at kafka.log.LogCleaner$CleanerThread.doWork(LogCleaner.scala:220)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:63)
Caused by: java.nio.file.FileSystemException: \tmp\kafka-logs\__consumer_offsets-7\00000000000000000000.log.cleaned -> \tmp\kafka-logs\__consumer_offsets-7\00000000000000000000.log.swap: El proceso no tiene acceso al archivo porque está siendo utilizado por otro proceso.

	at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:86)
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
	at sun.nio.fs.WindowsFileCopy.move(WindowsFileCopy.java:387)
	at sun.nio.fs.WindowsFileSystemProvider.move(WindowsFileSystemProvider.java:287)
	at java.nio.file.Files.move(Files.java:1395)
	at org.apache.kafka.common.utils.Utils.atomicMoveWithFallback(Utils.java:711)
	at org.apache.kafka.common.record.FileRecords.renameTo(FileRecords.java:210)
	... 10 more
	Suppressed: java.nio.file.FileSystemException: \tmp\kafka-logs\__consumer_offsets-7\00000000000000000000.log.cleaned -> \tmp\kafka-logs\__consumer_offsets-7\00000000000000000000.log.swap: El proceso no tiene acceso al archivo porque está siendo utilizado por otro proceso.

		at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:86)
		at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
		at sun.nio.fs.WindowsFileCopy.move(WindowsFileCopy.java:301)
		at sun.nio.fs.WindowsFileSystemProvider.move(WindowsFileSystemProvider.java:287)
		at java.nio.file.Files.move(Files.java:1395)
		at org.apache.kafka.common.utils.Utils.atomicMoveWithFallback(Utils.java:708)
		... 11 more
[2017-03-28 20:09:46,160] INFO [kafka-log-cleaner-thread-0], Stopped  (kafka.log.LogCleaner)
[2017-03-29 18:17:19,900] INFO Starting the log cleaner (kafka.log.LogCleaner)
[2017-03-29 18:17:19,903] INFO [kafka-log-cleaner-thread-0], Starting  (kafka.log.LogCleaner)
[2017-03-29 18:17:19,930] INFO Cleaner 0: Beginning cleaning of log __consumer_offsets-7. (kafka.log.LogCleaner)
[2017-03-29 18:17:19,930] INFO Cleaner 0: Building offset map for __consumer_offsets-7... (kafka.log.LogCleaner)
[2017-03-29 18:17:19,969] INFO Cleaner 0: Building offset map for log __consumer_offsets-7 for 1 segments in offset range [0, 5). (kafka.log.LogCleaner)
[2017-03-29 18:17:19,978] INFO Cleaner 0: Offset map for log __consumer_offsets-7 complete. (kafka.log.LogCleaner)
[2017-03-29 18:17:19,984] INFO Cleaner 0: Cleaning log __consumer_offsets-7 (cleaning prior to Tue Mar 21 09:14:25 CET 2017, discarding tombstones prior to Thu Jan 01 01:00:00 CET 1970)... (kafka.log.LogCleaner)
[2017-03-29 18:17:19,989] INFO Cleaner 0: Cleaning segment 0 in log __consumer_offsets-7 (largest timestamp Tue Mar 21 09:14:21 CET 2017) into 0, retaining deletes. (kafka.log.LogCleaner)
[2017-03-29 18:17:20,032] INFO Cleaner 0: Swapping in cleaned segment 0 for segment(s) 0 in log __consumer_offsets-7. (kafka.log.LogCleaner)
[2017-03-29 18:17:20,047] ERROR [kafka-log-cleaner-thread-0], Error due to  (kafka.log.LogCleaner)
kafka.common.KafkaStorageException: Failed to change the log file suffix from .cleaned to .swap for log segment 0
	at kafka.log.LogSegment.kafkaStorageException$1(LogSegment.scala:340)
	at kafka.log.LogSegment.changeFileSuffixes(LogSegment.scala:342)
	at kafka.log.Log.replaceSegments(Log.scala:1018)
	at kafka.log.Cleaner.cleanSegments(LogCleaner.scala:426)
	at kafka.log.Cleaner$$anonfun$clean$4.apply(LogCleaner.scala:363)
	at kafka.log.Cleaner$$anonfun$clean$4.apply(LogCleaner.scala:362)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at kafka.log.Cleaner.clean(LogCleaner.scala:362)
	at kafka.log.LogCleaner$CleanerThread.cleanOrSleep(LogCleaner.scala:241)
	at kafka.log.LogCleaner$CleanerThread.doWork(LogCleaner.scala:220)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:63)
Caused by: java.nio.file.FileSystemException: \tmp\kafka-logs\__consumer_offsets-7\00000000000000000000.log.cleaned -> \tmp\kafka-logs\__consumer_offsets-7\00000000000000000000.log.swap: El proceso no tiene acceso al archivo porque está siendo utilizado por otro proceso.

	at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:86)
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
	at sun.nio.fs.WindowsFileCopy.move(WindowsFileCopy.java:387)
	at sun.nio.fs.WindowsFileSystemProvider.move(WindowsFileSystemProvider.java:287)
	at java.nio.file.Files.move(Files.java:1395)
	at org.apache.kafka.common.utils.Utils.atomicMoveWithFallback(Utils.java:711)
	at org.apache.kafka.common.record.FileRecords.renameTo(FileRecords.java:210)
	... 10 more
	Suppressed: java.nio.file.FileSystemException: \tmp\kafka-logs\__consumer_offsets-7\00000000000000000000.log.cleaned -> \tmp\kafka-logs\__consumer_offsets-7\00000000000000000000.log.swap: El proceso no tiene acceso al archivo porque está siendo utilizado por otro proceso.

		at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:86)
		at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
		at sun.nio.fs.WindowsFileCopy.move(WindowsFileCopy.java:301)
		at sun.nio.fs.WindowsFileSystemProvider.move(WindowsFileSystemProvider.java:287)
		at java.nio.file.Files.move(Files.java:1395)
		at org.apache.kafka.common.utils.Utils.atomicMoveWithFallback(Utils.java:708)
		... 11 more
[2017-03-29 18:17:20,052] INFO [kafka-log-cleaner-thread-0], Stopped  (kafka.log.LogCleaner)
[2017-03-30 08:22:20,624] INFO Starting the log cleaner (kafka.log.LogCleaner)
[2017-03-30 08:22:20,627] INFO [kafka-log-cleaner-thread-0], Starting  (kafka.log.LogCleaner)
[2017-03-30 08:22:20,678] INFO Cleaner 0: Beginning cleaning of log __consumer_offsets-7. (kafka.log.LogCleaner)
[2017-03-30 08:22:20,679] INFO Cleaner 0: Building offset map for __consumer_offsets-7... (kafka.log.LogCleaner)
[2017-03-30 08:22:20,726] INFO Cleaner 0: Building offset map for log __consumer_offsets-7 for 1 segments in offset range [0, 5). (kafka.log.LogCleaner)
[2017-03-30 08:22:20,736] INFO Cleaner 0: Offset map for log __consumer_offsets-7 complete. (kafka.log.LogCleaner)
[2017-03-30 08:22:20,741] INFO Cleaner 0: Cleaning log __consumer_offsets-7 (cleaning prior to Tue Mar 21 09:14:25 CET 2017, discarding tombstones prior to Thu Jan 01 01:00:00 CET 1970)... (kafka.log.LogCleaner)
[2017-03-30 08:22:20,746] INFO Cleaner 0: Cleaning segment 0 in log __consumer_offsets-7 (largest timestamp Tue Mar 21 09:14:21 CET 2017) into 0, retaining deletes. (kafka.log.LogCleaner)
[2017-03-30 08:22:20,787] INFO Cleaner 0: Swapping in cleaned segment 0 for segment(s) 0 in log __consumer_offsets-7. (kafka.log.LogCleaner)
[2017-03-30 08:22:20,801] ERROR [kafka-log-cleaner-thread-0], Error due to  (kafka.log.LogCleaner)
kafka.common.KafkaStorageException: Failed to change the log file suffix from .cleaned to .swap for log segment 0
	at kafka.log.LogSegment.kafkaStorageException$1(LogSegment.scala:340)
	at kafka.log.LogSegment.changeFileSuffixes(LogSegment.scala:342)
	at kafka.log.Log.replaceSegments(Log.scala:1018)
	at kafka.log.Cleaner.cleanSegments(LogCleaner.scala:426)
	at kafka.log.Cleaner$$anonfun$clean$4.apply(LogCleaner.scala:363)
	at kafka.log.Cleaner$$anonfun$clean$4.apply(LogCleaner.scala:362)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at kafka.log.Cleaner.clean(LogCleaner.scala:362)
	at kafka.log.LogCleaner$CleanerThread.cleanOrSleep(LogCleaner.scala:241)
	at kafka.log.LogCleaner$CleanerThread.doWork(LogCleaner.scala:220)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:63)
Caused by: java.nio.file.FileSystemException: \tmp\kafka-logs\__consumer_offsets-7\00000000000000000000.log.cleaned -> \tmp\kafka-logs\__consumer_offsets-7\00000000000000000000.log.swap: El proceso no tiene acceso al archivo porque está siendo utilizado por otro proceso.

	at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:86)
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
	at sun.nio.fs.WindowsFileCopy.move(WindowsFileCopy.java:387)
	at sun.nio.fs.WindowsFileSystemProvider.move(WindowsFileSystemProvider.java:287)
	at java.nio.file.Files.move(Files.java:1395)
	at org.apache.kafka.common.utils.Utils.atomicMoveWithFallback(Utils.java:711)
	at org.apache.kafka.common.record.FileRecords.renameTo(FileRecords.java:210)
	... 10 more
	Suppressed: java.nio.file.FileSystemException: \tmp\kafka-logs\__consumer_offsets-7\00000000000000000000.log.cleaned -> \tmp\kafka-logs\__consumer_offsets-7\00000000000000000000.log.swap: El proceso no tiene acceso al archivo porque está siendo utilizado por otro proceso.

		at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:86)
		at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
		at sun.nio.fs.WindowsFileCopy.move(WindowsFileCopy.java:301)
		at sun.nio.fs.WindowsFileSystemProvider.move(WindowsFileSystemProvider.java:287)
		at java.nio.file.Files.move(Files.java:1395)
		at org.apache.kafka.common.utils.Utils.atomicMoveWithFallback(Utils.java:708)
		... 11 more
[2017-03-30 08:22:20,806] INFO [kafka-log-cleaner-thread-0], Stopped  (kafka.log.LogCleaner)
[2017-03-30 08:38:10,049] INFO Starting the log cleaner (kafka.log.LogCleaner)
[2017-03-30 08:38:10,050] INFO [kafka-log-cleaner-thread-0], Starting  (kafka.log.LogCleaner)
[2017-03-30 08:38:10,071] INFO Cleaner 0: Beginning cleaning of log __consumer_offsets-7. (kafka.log.LogCleaner)
[2017-03-30 08:38:10,071] INFO Cleaner 0: Building offset map for __consumer_offsets-7... (kafka.log.LogCleaner)
[2017-03-30 08:38:10,108] INFO Cleaner 0: Building offset map for log __consumer_offsets-7 for 1 segments in offset range [0, 5). (kafka.log.LogCleaner)
[2017-03-30 08:38:10,116] INFO Cleaner 0: Offset map for log __consumer_offsets-7 complete. (kafka.log.LogCleaner)
[2017-03-30 08:38:10,122] INFO Cleaner 0: Cleaning log __consumer_offsets-7 (cleaning prior to Tue Mar 21 09:14:25 CET 2017, discarding tombstones prior to Thu Jan 01 01:00:00 CET 1970)... (kafka.log.LogCleaner)
[2017-03-30 08:38:10,127] INFO Cleaner 0: Cleaning segment 0 in log __consumer_offsets-7 (largest timestamp Tue Mar 21 09:14:21 CET 2017) into 0, retaining deletes. (kafka.log.LogCleaner)
[2017-03-30 08:38:10,166] INFO Cleaner 0: Swapping in cleaned segment 0 for segment(s) 0 in log __consumer_offsets-7. (kafka.log.LogCleaner)
[2017-03-30 08:38:10,180] ERROR [kafka-log-cleaner-thread-0], Error due to  (kafka.log.LogCleaner)
kafka.common.KafkaStorageException: Failed to change the log file suffix from .cleaned to .swap for log segment 0
	at kafka.log.LogSegment.kafkaStorageException$1(LogSegment.scala:340)
	at kafka.log.LogSegment.changeFileSuffixes(LogSegment.scala:342)
	at kafka.log.Log.replaceSegments(Log.scala:1018)
	at kafka.log.Cleaner.cleanSegments(LogCleaner.scala:426)
	at kafka.log.Cleaner$$anonfun$clean$4.apply(LogCleaner.scala:363)
	at kafka.log.Cleaner$$anonfun$clean$4.apply(LogCleaner.scala:362)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at kafka.log.Cleaner.clean(LogCleaner.scala:362)
	at kafka.log.LogCleaner$CleanerThread.cleanOrSleep(LogCleaner.scala:241)
	at kafka.log.LogCleaner$CleanerThread.doWork(LogCleaner.scala:220)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:63)
Caused by: java.nio.file.FileSystemException: \tmp\kafka-logs\__consumer_offsets-7\00000000000000000000.log.cleaned -> \tmp\kafka-logs\__consumer_offsets-7\00000000000000000000.log.swap: El proceso no tiene acceso al archivo porque está siendo utilizado por otro proceso.

	at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:86)
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
	at sun.nio.fs.WindowsFileCopy.move(WindowsFileCopy.java:387)
	at sun.nio.fs.WindowsFileSystemProvider.move(WindowsFileSystemProvider.java:287)
	at java.nio.file.Files.move(Files.java:1395)
	at org.apache.kafka.common.utils.Utils.atomicMoveWithFallback(Utils.java:711)
	at org.apache.kafka.common.record.FileRecords.renameTo(FileRecords.java:210)
	... 10 more
	Suppressed: java.nio.file.FileSystemException: \tmp\kafka-logs\__consumer_offsets-7\00000000000000000000.log.cleaned -> \tmp\kafka-logs\__consumer_offsets-7\00000000000000000000.log.swap: El proceso no tiene acceso al archivo porque está siendo utilizado por otro proceso.

		at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:86)
		at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
		at sun.nio.fs.WindowsFileCopy.move(WindowsFileCopy.java:301)
		at sun.nio.fs.WindowsFileSystemProvider.move(WindowsFileSystemProvider.java:287)
		at java.nio.file.Files.move(Files.java:1395)
		at org.apache.kafka.common.utils.Utils.atomicMoveWithFallback(Utils.java:708)
		... 11 more
[2017-03-30 08:38:10,184] INFO [kafka-log-cleaner-thread-0], Stopped  (kafka.log.LogCleaner)
[2017-03-30 16:53:57,894] INFO Starting the log cleaner (kafka.log.LogCleaner)
[2017-03-30 16:53:57,897] INFO [kafka-log-cleaner-thread-0], Starting  (kafka.log.LogCleaner)
[2017-03-30 16:53:57,926] INFO Cleaner 0: Beginning cleaning of log __consumer_offsets-7. (kafka.log.LogCleaner)
[2017-03-30 16:53:57,927] INFO Cleaner 0: Building offset map for __consumer_offsets-7... (kafka.log.LogCleaner)
[2017-03-30 16:53:57,967] INFO Cleaner 0: Building offset map for log __consumer_offsets-7 for 1 segments in offset range [0, 5). (kafka.log.LogCleaner)
[2017-03-30 16:53:57,977] INFO Cleaner 0: Offset map for log __consumer_offsets-7 complete. (kafka.log.LogCleaner)
[2017-03-30 16:53:57,984] INFO Cleaner 0: Cleaning log __consumer_offsets-7 (cleaning prior to Tue Mar 21 09:14:25 CET 2017, discarding tombstones prior to Thu Jan 01 01:00:00 CET 1970)... (kafka.log.LogCleaner)
[2017-03-30 16:53:57,988] INFO Cleaner 0: Cleaning segment 0 in log __consumer_offsets-7 (largest timestamp Tue Mar 21 09:14:21 CET 2017) into 0, retaining deletes. (kafka.log.LogCleaner)
[2017-03-30 16:53:58,043] INFO Cleaner 0: Swapping in cleaned segment 0 for segment(s) 0 in log __consumer_offsets-7. (kafka.log.LogCleaner)
[2017-03-30 16:53:58,061] ERROR [kafka-log-cleaner-thread-0], Error due to  (kafka.log.LogCleaner)
kafka.common.KafkaStorageException: Failed to change the log file suffix from .cleaned to .swap for log segment 0
	at kafka.log.LogSegment.kafkaStorageException$1(LogSegment.scala:340)
	at kafka.log.LogSegment.changeFileSuffixes(LogSegment.scala:342)
	at kafka.log.Log.replaceSegments(Log.scala:1018)
	at kafka.log.Cleaner.cleanSegments(LogCleaner.scala:426)
	at kafka.log.Cleaner$$anonfun$clean$4.apply(LogCleaner.scala:363)
	at kafka.log.Cleaner$$anonfun$clean$4.apply(LogCleaner.scala:362)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at kafka.log.Cleaner.clean(LogCleaner.scala:362)
	at kafka.log.LogCleaner$CleanerThread.cleanOrSleep(LogCleaner.scala:241)
	at kafka.log.LogCleaner$CleanerThread.doWork(LogCleaner.scala:220)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:63)
Caused by: java.nio.file.FileSystemException: \tmp\kafka-logs\__consumer_offsets-7\00000000000000000000.log.cleaned -> \tmp\kafka-logs\__consumer_offsets-7\00000000000000000000.log.swap: El proceso no tiene acceso al archivo porque está siendo utilizado por otro proceso.

	at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:86)
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
	at sun.nio.fs.WindowsFileCopy.move(WindowsFileCopy.java:387)
	at sun.nio.fs.WindowsFileSystemProvider.move(WindowsFileSystemProvider.java:287)
	at java.nio.file.Files.move(Files.java:1395)
	at org.apache.kafka.common.utils.Utils.atomicMoveWithFallback(Utils.java:711)
	at org.apache.kafka.common.record.FileRecords.renameTo(FileRecords.java:210)
	... 10 more
	Suppressed: java.nio.file.FileSystemException: \tmp\kafka-logs\__consumer_offsets-7\00000000000000000000.log.cleaned -> \tmp\kafka-logs\__consumer_offsets-7\00000000000000000000.log.swap: El proceso no tiene acceso al archivo porque está siendo utilizado por otro proceso.

		at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:86)
		at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
		at sun.nio.fs.WindowsFileCopy.move(WindowsFileCopy.java:301)
		at sun.nio.fs.WindowsFileSystemProvider.move(WindowsFileSystemProvider.java:287)
		at java.nio.file.Files.move(Files.java:1395)
		at org.apache.kafka.common.utils.Utils.atomicMoveWithFallback(Utils.java:708)
		... 11 more
[2017-03-30 16:53:58,066] INFO [kafka-log-cleaner-thread-0], Stopped  (kafka.log.LogCleaner)
[2017-03-30 22:57:52,660] INFO Starting the log cleaner (kafka.log.LogCleaner)
[2017-03-30 22:57:52,660] INFO [kafka-log-cleaner-thread-0], Starting  (kafka.log.LogCleaner)
[2017-03-30 22:57:52,691] INFO Cleaner 0: Beginning cleaning of log __consumer_offsets-7. (kafka.log.LogCleaner)
[2017-03-30 22:57:52,691] INFO Cleaner 0: Building offset map for __consumer_offsets-7... (kafka.log.LogCleaner)
[2017-03-30 22:57:52,738] INFO Cleaner 0: Building offset map for log __consumer_offsets-7 for 1 segments in offset range [0, 5). (kafka.log.LogCleaner)
[2017-03-30 22:57:52,738] INFO Cleaner 0: Offset map for log __consumer_offsets-7 complete. (kafka.log.LogCleaner)
[2017-03-30 22:57:52,754] INFO Cleaner 0: Cleaning log __consumer_offsets-7 (cleaning prior to Tue Mar 21 09:14:25 CET 2017, discarding tombstones prior to Thu Jan 01 01:00:00 CET 1970)... (kafka.log.LogCleaner)
[2017-03-30 22:57:52,754] INFO Cleaner 0: Cleaning segment 0 in log __consumer_offsets-7 (largest timestamp Tue Mar 21 09:14:21 CET 2017) into 0, retaining deletes. (kafka.log.LogCleaner)
[2017-03-30 22:57:52,801] INFO Cleaner 0: Swapping in cleaned segment 0 for segment(s) 0 in log __consumer_offsets-7. (kafka.log.LogCleaner)
[2017-03-30 22:57:52,816] ERROR [kafka-log-cleaner-thread-0], Error due to  (kafka.log.LogCleaner)
kafka.common.KafkaStorageException: Failed to change the log file suffix from .cleaned to .swap for log segment 0
	at kafka.log.LogSegment.kafkaStorageException$1(LogSegment.scala:340)
	at kafka.log.LogSegment.changeFileSuffixes(LogSegment.scala:342)
	at kafka.log.Log.replaceSegments(Log.scala:1018)
	at kafka.log.Cleaner.cleanSegments(LogCleaner.scala:426)
	at kafka.log.Cleaner$$anonfun$clean$4.apply(LogCleaner.scala:363)
	at kafka.log.Cleaner$$anonfun$clean$4.apply(LogCleaner.scala:362)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at kafka.log.Cleaner.clean(LogCleaner.scala:362)
	at kafka.log.LogCleaner$CleanerThread.cleanOrSleep(LogCleaner.scala:241)
	at kafka.log.LogCleaner$CleanerThread.doWork(LogCleaner.scala:220)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:63)
Caused by: java.nio.file.FileSystemException: \tmp\kafka-logs\__consumer_offsets-7\00000000000000000000.log.cleaned -> \tmp\kafka-logs\__consumer_offsets-7\00000000000000000000.log.swap: El proceso no tiene acceso al archivo porque está siendo utilizado por otro proceso.

	at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:86)
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
	at sun.nio.fs.WindowsFileCopy.move(WindowsFileCopy.java:387)
	at sun.nio.fs.WindowsFileSystemProvider.move(WindowsFileSystemProvider.java:287)
	at java.nio.file.Files.move(Files.java:1395)
	at org.apache.kafka.common.utils.Utils.atomicMoveWithFallback(Utils.java:711)
	at org.apache.kafka.common.record.FileRecords.renameTo(FileRecords.java:210)
	... 10 more
	Suppressed: java.nio.file.FileSystemException: \tmp\kafka-logs\__consumer_offsets-7\00000000000000000000.log.cleaned -> \tmp\kafka-logs\__consumer_offsets-7\00000000000000000000.log.swap: El proceso no tiene acceso al archivo porque está siendo utilizado por otro proceso.

		at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:86)
		at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
		at sun.nio.fs.WindowsFileCopy.move(WindowsFileCopy.java:301)
		at sun.nio.fs.WindowsFileSystemProvider.move(WindowsFileSystemProvider.java:287)
		at java.nio.file.Files.move(Files.java:1395)
		at org.apache.kafka.common.utils.Utils.atomicMoveWithFallback(Utils.java:708)
		... 11 more
[2017-03-30 22:57:52,816] INFO [kafka-log-cleaner-thread-0], Stopped  (kafka.log.LogCleaner)
[2017-03-31 17:36:12,121] INFO Starting the log cleaner (kafka.log.LogCleaner)
[2017-03-31 17:36:12,125] INFO [kafka-log-cleaner-thread-0], Starting  (kafka.log.LogCleaner)
[2017-03-31 17:36:12,173] INFO Cleaner 0: Beginning cleaning of log __consumer_offsets-7. (kafka.log.LogCleaner)
[2017-03-31 17:36:12,173] INFO Cleaner 0: Building offset map for __consumer_offsets-7... (kafka.log.LogCleaner)
[2017-03-31 17:36:12,226] INFO Cleaner 0: Building offset map for log __consumer_offsets-7 for 1 segments in offset range [0, 5). (kafka.log.LogCleaner)
[2017-03-31 17:36:12,239] INFO Cleaner 0: Offset map for log __consumer_offsets-7 complete. (kafka.log.LogCleaner)
[2017-03-31 17:36:12,247] INFO Cleaner 0: Cleaning log __consumer_offsets-7 (cleaning prior to Tue Mar 21 09:14:25 CET 2017, discarding tombstones prior to Thu Jan 01 01:00:00 CET 1970)... (kafka.log.LogCleaner)
[2017-03-31 17:36:12,254] INFO Cleaner 0: Cleaning segment 0 in log __consumer_offsets-7 (largest timestamp Tue Mar 21 09:14:21 CET 2017) into 0, retaining deletes. (kafka.log.LogCleaner)
[2017-03-31 17:36:12,321] INFO Cleaner 0: Swapping in cleaned segment 0 for segment(s) 0 in log __consumer_offsets-7. (kafka.log.LogCleaner)
[2017-03-31 17:36:12,346] ERROR [kafka-log-cleaner-thread-0], Error due to  (kafka.log.LogCleaner)
kafka.common.KafkaStorageException: Failed to change the log file suffix from .cleaned to .swap for log segment 0
	at kafka.log.LogSegment.kafkaStorageException$1(LogSegment.scala:340)
	at kafka.log.LogSegment.changeFileSuffixes(LogSegment.scala:342)
	at kafka.log.Log.replaceSegments(Log.scala:1018)
	at kafka.log.Cleaner.cleanSegments(LogCleaner.scala:426)
	at kafka.log.Cleaner$$anonfun$clean$4.apply(LogCleaner.scala:363)
	at kafka.log.Cleaner$$anonfun$clean$4.apply(LogCleaner.scala:362)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at kafka.log.Cleaner.clean(LogCleaner.scala:362)
	at kafka.log.LogCleaner$CleanerThread.cleanOrSleep(LogCleaner.scala:241)
	at kafka.log.LogCleaner$CleanerThread.doWork(LogCleaner.scala:220)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:63)
Caused by: java.nio.file.FileSystemException: \tmp\kafka-logs\__consumer_offsets-7\00000000000000000000.log.cleaned -> \tmp\kafka-logs\__consumer_offsets-7\00000000000000000000.log.swap: El proceso no tiene acceso al archivo porque está siendo utilizado por otro proceso.

	at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:86)
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
	at sun.nio.fs.WindowsFileCopy.move(WindowsFileCopy.java:387)
	at sun.nio.fs.WindowsFileSystemProvider.move(WindowsFileSystemProvider.java:287)
	at java.nio.file.Files.move(Files.java:1395)
	at org.apache.kafka.common.utils.Utils.atomicMoveWithFallback(Utils.java:711)
	at org.apache.kafka.common.record.FileRecords.renameTo(FileRecords.java:210)
	... 10 more
	Suppressed: java.nio.file.FileSystemException: \tmp\kafka-logs\__consumer_offsets-7\00000000000000000000.log.cleaned -> \tmp\kafka-logs\__consumer_offsets-7\00000000000000000000.log.swap: El proceso no tiene acceso al archivo porque está siendo utilizado por otro proceso.

		at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:86)
		at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
		at sun.nio.fs.WindowsFileCopy.move(WindowsFileCopy.java:301)
		at sun.nio.fs.WindowsFileSystemProvider.move(WindowsFileSystemProvider.java:287)
		at java.nio.file.Files.move(Files.java:1395)
		at org.apache.kafka.common.utils.Utils.atomicMoveWithFallback(Utils.java:708)
		... 11 more
[2017-03-31 17:36:12,356] INFO [kafka-log-cleaner-thread-0], Stopped  (kafka.log.LogCleaner)
[2017-03-31 18:57:32,285] INFO Starting the log cleaner (kafka.log.LogCleaner)
[2017-03-31 18:57:32,288] INFO [kafka-log-cleaner-thread-0], Starting  (kafka.log.LogCleaner)
[2017-03-31 18:57:32,312] INFO Cleaner 0: Beginning cleaning of log __consumer_offsets-26. (kafka.log.LogCleaner)
[2017-03-31 18:57:32,312] INFO Cleaner 0: Building offset map for __consumer_offsets-26... (kafka.log.LogCleaner)
[2017-03-31 18:57:32,354] INFO Cleaner 0: Building offset map for log __consumer_offsets-26 for 1 segments in offset range [0, 26). (kafka.log.LogCleaner)
[2017-03-31 18:57:32,364] INFO Cleaner 0: Offset map for log __consumer_offsets-26 complete. (kafka.log.LogCleaner)
[2017-03-31 18:57:32,372] INFO Cleaner 0: Cleaning log __consumer_offsets-26 (cleaning prior to Thu Mar 30 18:10:58 CEST 2017, discarding tombstones prior to Thu Jan 01 01:00:00 CET 1970)... (kafka.log.LogCleaner)
[2017-03-31 18:57:32,379] INFO Cleaner 0: Cleaning segment 0 in log __consumer_offsets-26 (largest timestamp Thu Mar 30 18:10:50 CEST 2017) into 0, retaining deletes. (kafka.log.LogCleaner)
[2017-03-31 18:57:32,430] INFO Cleaner 0: Swapping in cleaned segment 0 for segment(s) 0 in log __consumer_offsets-26. (kafka.log.LogCleaner)
[2017-03-31 18:57:32,453] ERROR [kafka-log-cleaner-thread-0], Error due to  (kafka.log.LogCleaner)
kafka.common.KafkaStorageException: Failed to change the log file suffix from .cleaned to .swap for log segment 0
	at kafka.log.LogSegment.kafkaStorageException$1(LogSegment.scala:340)
	at kafka.log.LogSegment.changeFileSuffixes(LogSegment.scala:342)
	at kafka.log.Log.replaceSegments(Log.scala:1018)
	at kafka.log.Cleaner.cleanSegments(LogCleaner.scala:426)
	at kafka.log.Cleaner$$anonfun$clean$4.apply(LogCleaner.scala:363)
	at kafka.log.Cleaner$$anonfun$clean$4.apply(LogCleaner.scala:362)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at kafka.log.Cleaner.clean(LogCleaner.scala:362)
	at kafka.log.LogCleaner$CleanerThread.cleanOrSleep(LogCleaner.scala:241)
	at kafka.log.LogCleaner$CleanerThread.doWork(LogCleaner.scala:220)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:63)
Caused by: java.nio.file.FileSystemException: \tmp\kafka-logs\__consumer_offsets-26\00000000000000000000.log.cleaned -> \tmp\kafka-logs\__consumer_offsets-26\00000000000000000000.log.swap: El proceso no tiene acceso al archivo porque está siendo utilizado por otro proceso.

	at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:86)
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
	at sun.nio.fs.WindowsFileCopy.move(WindowsFileCopy.java:387)
	at sun.nio.fs.WindowsFileSystemProvider.move(WindowsFileSystemProvider.java:287)
	at java.nio.file.Files.move(Files.java:1395)
	at org.apache.kafka.common.utils.Utils.atomicMoveWithFallback(Utils.java:711)
	at org.apache.kafka.common.record.FileRecords.renameTo(FileRecords.java:210)
	... 10 more
	Suppressed: java.nio.file.FileSystemException: \tmp\kafka-logs\__consumer_offsets-26\00000000000000000000.log.cleaned -> \tmp\kafka-logs\__consumer_offsets-26\00000000000000000000.log.swap: El proceso no tiene acceso al archivo porque está siendo utilizado por otro proceso.

		at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:86)
		at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
		at sun.nio.fs.WindowsFileCopy.move(WindowsFileCopy.java:301)
		at sun.nio.fs.WindowsFileSystemProvider.move(WindowsFileSystemProvider.java:287)
		at java.nio.file.Files.move(Files.java:1395)
		at org.apache.kafka.common.utils.Utils.atomicMoveWithFallback(Utils.java:708)
		... 11 more
[2017-03-31 18:57:32,458] INFO [kafka-log-cleaner-thread-0], Stopped  (kafka.log.LogCleaner)
[2017-04-01 12:42:34,565] INFO Starting the log cleaner (kafka.log.LogCleaner)
[2017-04-01 12:42:34,569] INFO [kafka-log-cleaner-thread-0], Starting  (kafka.log.LogCleaner)
[2017-04-01 12:42:34,600] INFO Cleaner 0: Beginning cleaning of log __consumer_offsets-26. (kafka.log.LogCleaner)
[2017-04-01 12:42:34,601] INFO Cleaner 0: Building offset map for __consumer_offsets-26... (kafka.log.LogCleaner)
[2017-04-01 12:42:34,643] INFO Cleaner 0: Building offset map for log __consumer_offsets-26 for 1 segments in offset range [0, 26). (kafka.log.LogCleaner)
[2017-04-01 12:42:34,654] INFO Cleaner 0: Offset map for log __consumer_offsets-26 complete. (kafka.log.LogCleaner)
[2017-04-01 12:42:34,662] INFO Cleaner 0: Cleaning log __consumer_offsets-26 (cleaning prior to Thu Mar 30 18:10:58 CEST 2017, discarding tombstones prior to Thu Jan 01 01:00:00 CET 1970)... (kafka.log.LogCleaner)
[2017-04-01 12:42:34,669] INFO Cleaner 0: Cleaning segment 0 in log __consumer_offsets-26 (largest timestamp Thu Mar 30 18:10:50 CEST 2017) into 0, retaining deletes. (kafka.log.LogCleaner)
[2017-04-01 12:42:34,723] INFO Cleaner 0: Swapping in cleaned segment 0 for segment(s) 0 in log __consumer_offsets-26. (kafka.log.LogCleaner)
[2017-04-01 12:42:34,741] ERROR [kafka-log-cleaner-thread-0], Error due to  (kafka.log.LogCleaner)
kafka.common.KafkaStorageException: Failed to change the log file suffix from .cleaned to .swap for log segment 0
	at kafka.log.LogSegment.kafkaStorageException$1(LogSegment.scala:340)
	at kafka.log.LogSegment.changeFileSuffixes(LogSegment.scala:342)
	at kafka.log.Log.replaceSegments(Log.scala:1018)
	at kafka.log.Cleaner.cleanSegments(LogCleaner.scala:426)
	at kafka.log.Cleaner$$anonfun$clean$4.apply(LogCleaner.scala:363)
	at kafka.log.Cleaner$$anonfun$clean$4.apply(LogCleaner.scala:362)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at kafka.log.Cleaner.clean(LogCleaner.scala:362)
	at kafka.log.LogCleaner$CleanerThread.cleanOrSleep(LogCleaner.scala:241)
	at kafka.log.LogCleaner$CleanerThread.doWork(LogCleaner.scala:220)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:63)
Caused by: java.nio.file.FileSystemException: \tmp\kafka-logs\__consumer_offsets-26\00000000000000000000.log.cleaned -> \tmp\kafka-logs\__consumer_offsets-26\00000000000000000000.log.swap: El proceso no tiene acceso al archivo porque está siendo utilizado por otro proceso.

	at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:86)
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
	at sun.nio.fs.WindowsFileCopy.move(WindowsFileCopy.java:387)
	at sun.nio.fs.WindowsFileSystemProvider.move(WindowsFileSystemProvider.java:287)
	at java.nio.file.Files.move(Files.java:1395)
	at org.apache.kafka.common.utils.Utils.atomicMoveWithFallback(Utils.java:711)
	at org.apache.kafka.common.record.FileRecords.renameTo(FileRecords.java:210)
	... 10 more
	Suppressed: java.nio.file.FileSystemException: \tmp\kafka-logs\__consumer_offsets-26\00000000000000000000.log.cleaned -> \tmp\kafka-logs\__consumer_offsets-26\00000000000000000000.log.swap: El proceso no tiene acceso al archivo porque está siendo utilizado por otro proceso.

		at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:86)
		at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
		at sun.nio.fs.WindowsFileCopy.move(WindowsFileCopy.java:301)
		at sun.nio.fs.WindowsFileSystemProvider.move(WindowsFileSystemProvider.java:287)
		at java.nio.file.Files.move(Files.java:1395)
		at org.apache.kafka.common.utils.Utils.atomicMoveWithFallback(Utils.java:708)
		... 11 more
[2017-04-01 12:42:34,748] INFO [kafka-log-cleaner-thread-0], Stopped  (kafka.log.LogCleaner)
[2017-04-01 17:29:16,829] INFO Starting the log cleaner (kafka.log.LogCleaner)
[2017-04-01 17:29:16,833] INFO [kafka-log-cleaner-thread-0], Starting  (kafka.log.LogCleaner)
[2017-04-01 17:29:16,858] INFO Cleaner 0: Beginning cleaning of log __consumer_offsets-26. (kafka.log.LogCleaner)
[2017-04-01 17:29:16,859] INFO Cleaner 0: Building offset map for __consumer_offsets-26... (kafka.log.LogCleaner)
[2017-04-01 17:29:16,923] INFO Cleaner 0: Building offset map for log __consumer_offsets-26 for 1 segments in offset range [0, 26). (kafka.log.LogCleaner)
[2017-04-01 17:29:16,937] INFO Cleaner 0: Offset map for log __consumer_offsets-26 complete. (kafka.log.LogCleaner)
[2017-04-01 17:29:16,946] INFO Cleaner 0: Cleaning log __consumer_offsets-26 (cleaning prior to Thu Mar 30 18:10:58 CEST 2017, discarding tombstones prior to Thu Jan 01 01:00:00 CET 1970)... (kafka.log.LogCleaner)
[2017-04-01 17:29:16,955] INFO Cleaner 0: Cleaning segment 0 in log __consumer_offsets-26 (largest timestamp Thu Mar 30 18:10:50 CEST 2017) into 0, retaining deletes. (kafka.log.LogCleaner)
[2017-04-01 17:29:17,021] INFO Cleaner 0: Swapping in cleaned segment 0 for segment(s) 0 in log __consumer_offsets-26. (kafka.log.LogCleaner)
[2017-04-01 17:29:17,045] ERROR [kafka-log-cleaner-thread-0], Error due to  (kafka.log.LogCleaner)
kafka.common.KafkaStorageException: Failed to change the log file suffix from .cleaned to .swap for log segment 0
	at kafka.log.LogSegment.kafkaStorageException$1(LogSegment.scala:340)
	at kafka.log.LogSegment.changeFileSuffixes(LogSegment.scala:342)
	at kafka.log.Log.replaceSegments(Log.scala:1018)
	at kafka.log.Cleaner.cleanSegments(LogCleaner.scala:426)
	at kafka.log.Cleaner$$anonfun$clean$4.apply(LogCleaner.scala:363)
	at kafka.log.Cleaner$$anonfun$clean$4.apply(LogCleaner.scala:362)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at kafka.log.Cleaner.clean(LogCleaner.scala:362)
	at kafka.log.LogCleaner$CleanerThread.cleanOrSleep(LogCleaner.scala:241)
	at kafka.log.LogCleaner$CleanerThread.doWork(LogCleaner.scala:220)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:63)
Caused by: java.nio.file.FileSystemException: \tmp\kafka-logs\__consumer_offsets-26\00000000000000000000.log.cleaned -> \tmp\kafka-logs\__consumer_offsets-26\00000000000000000000.log.swap: El proceso no tiene acceso al archivo porque está siendo utilizado por otro proceso.

	at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:86)
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
	at sun.nio.fs.WindowsFileCopy.move(WindowsFileCopy.java:387)
	at sun.nio.fs.WindowsFileSystemProvider.move(WindowsFileSystemProvider.java:287)
	at java.nio.file.Files.move(Files.java:1395)
	at org.apache.kafka.common.utils.Utils.atomicMoveWithFallback(Utils.java:711)
	at org.apache.kafka.common.record.FileRecords.renameTo(FileRecords.java:210)
	... 10 more
	Suppressed: java.nio.file.FileSystemException: \tmp\kafka-logs\__consumer_offsets-26\00000000000000000000.log.cleaned -> \tmp\kafka-logs\__consumer_offsets-26\00000000000000000000.log.swap: El proceso no tiene acceso al archivo porque está siendo utilizado por otro proceso.

		at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:86)
		at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
		at sun.nio.fs.WindowsFileCopy.move(WindowsFileCopy.java:301)
		at sun.nio.fs.WindowsFileSystemProvider.move(WindowsFileSystemProvider.java:287)
		at java.nio.file.Files.move(Files.java:1395)
		at org.apache.kafka.common.utils.Utils.atomicMoveWithFallback(Utils.java:708)
		... 11 more
[2017-04-01 17:29:17,050] INFO [kafka-log-cleaner-thread-0], Stopped  (kafka.log.LogCleaner)
[2017-04-02 10:15:47,039] INFO Starting the log cleaner (kafka.log.LogCleaner)
[2017-04-02 10:15:47,042] INFO [kafka-log-cleaner-thread-0], Starting  (kafka.log.LogCleaner)
[2017-04-02 10:15:47,075] INFO Cleaner 0: Beginning cleaning of log __consumer_offsets-26. (kafka.log.LogCleaner)
[2017-04-02 10:15:47,075] INFO Cleaner 0: Building offset map for __consumer_offsets-26... (kafka.log.LogCleaner)
[2017-04-02 10:15:47,118] INFO Cleaner 0: Building offset map for log __consumer_offsets-26 for 1 segments in offset range [0, 26). (kafka.log.LogCleaner)
[2017-04-02 10:15:47,129] INFO Cleaner 0: Offset map for log __consumer_offsets-26 complete. (kafka.log.LogCleaner)
[2017-04-02 10:15:47,140] INFO Cleaner 0: Cleaning log __consumer_offsets-26 (cleaning prior to Thu Mar 30 18:10:58 CEST 2017, discarding tombstones prior to Thu Jan 01 01:00:00 CET 1970)... (kafka.log.LogCleaner)
[2017-04-02 10:15:47,145] INFO Cleaner 0: Cleaning segment 0 in log __consumer_offsets-26 (largest timestamp Thu Mar 30 18:10:50 CEST 2017) into 0, retaining deletes. (kafka.log.LogCleaner)
[2017-04-02 10:15:47,188] INFO Cleaner 0: Swapping in cleaned segment 0 for segment(s) 0 in log __consumer_offsets-26. (kafka.log.LogCleaner)
[2017-04-02 10:15:47,203] ERROR [kafka-log-cleaner-thread-0], Error due to  (kafka.log.LogCleaner)
kafka.common.KafkaStorageException: Failed to change the log file suffix from .cleaned to .swap for log segment 0
	at kafka.log.LogSegment.kafkaStorageException$1(LogSegment.scala:340)
	at kafka.log.LogSegment.changeFileSuffixes(LogSegment.scala:342)
	at kafka.log.Log.replaceSegments(Log.scala:1018)
	at kafka.log.Cleaner.cleanSegments(LogCleaner.scala:426)
	at kafka.log.Cleaner$$anonfun$clean$4.apply(LogCleaner.scala:363)
	at kafka.log.Cleaner$$anonfun$clean$4.apply(LogCleaner.scala:362)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at kafka.log.Cleaner.clean(LogCleaner.scala:362)
	at kafka.log.LogCleaner$CleanerThread.cleanOrSleep(LogCleaner.scala:241)
	at kafka.log.LogCleaner$CleanerThread.doWork(LogCleaner.scala:220)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:63)
Caused by: java.nio.file.FileSystemException: \tmp\kafka-logs\__consumer_offsets-26\00000000000000000000.log.cleaned -> \tmp\kafka-logs\__consumer_offsets-26\00000000000000000000.log.swap: El proceso no tiene acceso al archivo porque está siendo utilizado por otro proceso.

	at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:86)
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
	at sun.nio.fs.WindowsFileCopy.move(WindowsFileCopy.java:387)
	at sun.nio.fs.WindowsFileSystemProvider.move(WindowsFileSystemProvider.java:287)
	at java.nio.file.Files.move(Files.java:1395)
	at org.apache.kafka.common.utils.Utils.atomicMoveWithFallback(Utils.java:711)
	at org.apache.kafka.common.record.FileRecords.renameTo(FileRecords.java:210)
	... 10 more
	Suppressed: java.nio.file.FileSystemException: \tmp\kafka-logs\__consumer_offsets-26\00000000000000000000.log.cleaned -> \tmp\kafka-logs\__consumer_offsets-26\00000000000000000000.log.swap: El proceso no tiene acceso al archivo porque está siendo utilizado por otro proceso.

		at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:86)
		at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
		at sun.nio.fs.WindowsFileCopy.move(WindowsFileCopy.java:301)
		at sun.nio.fs.WindowsFileSystemProvider.move(WindowsFileSystemProvider.java:287)
		at java.nio.file.Files.move(Files.java:1395)
		at org.apache.kafka.common.utils.Utils.atomicMoveWithFallback(Utils.java:708)
		... 11 more
[2017-04-02 10:15:47,209] INFO [kafka-log-cleaner-thread-0], Stopped  (kafka.log.LogCleaner)
[2017-04-02 13:01:38,576] INFO Starting the log cleaner (kafka.log.LogCleaner)
[2017-04-02 13:01:38,616] INFO [kafka-log-cleaner-thread-0], Starting  (kafka.log.LogCleaner)
[2017-04-02 13:01:38,656] INFO Cleaner 0: Beginning cleaning of log __consumer_offsets-26. (kafka.log.LogCleaner)
[2017-04-02 13:01:38,657] INFO Cleaner 0: Building offset map for __consumer_offsets-26... (kafka.log.LogCleaner)
[2017-04-02 13:01:38,709] INFO Cleaner 0: Building offset map for log __consumer_offsets-26 for 1 segments in offset range [0, 26). (kafka.log.LogCleaner)
[2017-04-02 13:01:38,722] INFO Cleaner 0: Offset map for log __consumer_offsets-26 complete. (kafka.log.LogCleaner)
[2017-04-02 13:01:38,731] INFO Cleaner 0: Cleaning log __consumer_offsets-26 (cleaning prior to Thu Mar 30 18:10:58 CEST 2017, discarding tombstones prior to Thu Jan 01 01:00:00 CET 1970)... (kafka.log.LogCleaner)
[2017-04-02 13:01:38,737] INFO Cleaner 0: Cleaning segment 0 in log __consumer_offsets-26 (largest timestamp Thu Mar 30 18:10:50 CEST 2017) into 0, retaining deletes. (kafka.log.LogCleaner)
[2017-04-02 13:01:39,033] INFO Cleaner 0: Swapping in cleaned segment 0 for segment(s) 0 in log __consumer_offsets-26. (kafka.log.LogCleaner)
[2017-04-02 13:01:39,393] ERROR [kafka-log-cleaner-thread-0], Error due to  (kafka.log.LogCleaner)
kafka.common.KafkaStorageException: Failed to change the log file suffix from .cleaned to .swap for log segment 0
	at kafka.log.LogSegment.kafkaStorageException$1(LogSegment.scala:340)
	at kafka.log.LogSegment.changeFileSuffixes(LogSegment.scala:342)
	at kafka.log.Log.replaceSegments(Log.scala:1018)
	at kafka.log.Cleaner.cleanSegments(LogCleaner.scala:426)
	at kafka.log.Cleaner$$anonfun$clean$4.apply(LogCleaner.scala:363)
	at kafka.log.Cleaner$$anonfun$clean$4.apply(LogCleaner.scala:362)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at kafka.log.Cleaner.clean(LogCleaner.scala:362)
	at kafka.log.LogCleaner$CleanerThread.cleanOrSleep(LogCleaner.scala:241)
	at kafka.log.LogCleaner$CleanerThread.doWork(LogCleaner.scala:220)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:63)
Caused by: java.nio.file.FileSystemException: \tmp\kafka-logs\__consumer_offsets-26\00000000000000000000.log.cleaned -> \tmp\kafka-logs\__consumer_offsets-26\00000000000000000000.log.swap: El proceso no tiene acceso al archivo porque está siendo utilizado por otro proceso.

	at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:86)
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
	at sun.nio.fs.WindowsFileCopy.move(WindowsFileCopy.java:387)
	at sun.nio.fs.WindowsFileSystemProvider.move(WindowsFileSystemProvider.java:287)
	at java.nio.file.Files.move(Files.java:1395)
	at org.apache.kafka.common.utils.Utils.atomicMoveWithFallback(Utils.java:711)
	at org.apache.kafka.common.record.FileRecords.renameTo(FileRecords.java:210)
	... 10 more
	Suppressed: java.nio.file.FileSystemException: \tmp\kafka-logs\__consumer_offsets-26\00000000000000000000.log.cleaned -> \tmp\kafka-logs\__consumer_offsets-26\00000000000000000000.log.swap: El proceso no tiene acceso al archivo porque está siendo utilizado por otro proceso.

		at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:86)
		at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
		at sun.nio.fs.WindowsFileCopy.move(WindowsFileCopy.java:301)
		at sun.nio.fs.WindowsFileSystemProvider.move(WindowsFileSystemProvider.java:287)
		at java.nio.file.Files.move(Files.java:1395)
		at org.apache.kafka.common.utils.Utils.atomicMoveWithFallback(Utils.java:708)
		... 11 more
[2017-04-02 13:01:39,397] INFO [kafka-log-cleaner-thread-0], Stopped  (kafka.log.LogCleaner)
[2017-04-02 13:24:10,733] INFO Starting the log cleaner (kafka.log.LogCleaner)
[2017-04-02 13:24:10,733] INFO [kafka-log-cleaner-thread-0], Starting  (kafka.log.LogCleaner)
[2017-04-02 13:24:10,764] INFO Cleaner 0: Beginning cleaning of log __consumer_offsets-26. (kafka.log.LogCleaner)
[2017-04-02 13:24:10,764] INFO Cleaner 0: Building offset map for __consumer_offsets-26... (kafka.log.LogCleaner)
[2017-04-02 13:24:10,811] INFO Cleaner 0: Building offset map for log __consumer_offsets-26 for 1 segments in offset range [0, 26). (kafka.log.LogCleaner)
[2017-04-02 13:24:10,827] INFO Cleaner 0: Offset map for log __consumer_offsets-26 complete. (kafka.log.LogCleaner)
[2017-04-02 13:24:10,842] INFO Cleaner 0: Cleaning log __consumer_offsets-26 (cleaning prior to Thu Mar 30 18:10:58 CEST 2017, discarding tombstones prior to Thu Jan 01 01:00:00 CET 1970)... (kafka.log.LogCleaner)
[2017-04-02 13:24:10,842] INFO Cleaner 0: Cleaning segment 0 in log __consumer_offsets-26 (largest timestamp Thu Mar 30 18:10:50 CEST 2017) into 0, retaining deletes. (kafka.log.LogCleaner)
[2017-04-02 13:24:10,889] INFO Cleaner 0: Swapping in cleaned segment 0 for segment(s) 0 in log __consumer_offsets-26. (kafka.log.LogCleaner)
[2017-04-02 13:24:10,905] ERROR [kafka-log-cleaner-thread-0], Error due to  (kafka.log.LogCleaner)
kafka.common.KafkaStorageException: Failed to change the log file suffix from .cleaned to .swap for log segment 0
	at kafka.log.LogSegment.kafkaStorageException$1(LogSegment.scala:340)
	at kafka.log.LogSegment.changeFileSuffixes(LogSegment.scala:342)
	at kafka.log.Log.replaceSegments(Log.scala:1018)
	at kafka.log.Cleaner.cleanSegments(LogCleaner.scala:426)
	at kafka.log.Cleaner$$anonfun$clean$4.apply(LogCleaner.scala:363)
	at kafka.log.Cleaner$$anonfun$clean$4.apply(LogCleaner.scala:362)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at kafka.log.Cleaner.clean(LogCleaner.scala:362)
	at kafka.log.LogCleaner$CleanerThread.cleanOrSleep(LogCleaner.scala:241)
	at kafka.log.LogCleaner$CleanerThread.doWork(LogCleaner.scala:220)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:63)
Caused by: java.nio.file.FileSystemException: \tmp\kafka-logs\__consumer_offsets-26\00000000000000000000.log.cleaned -> \tmp\kafka-logs\__consumer_offsets-26\00000000000000000000.log.swap: El proceso no tiene acceso al archivo porque está siendo utilizado por otro proceso.

	at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:86)
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
	at sun.nio.fs.WindowsFileCopy.move(WindowsFileCopy.java:387)
	at sun.nio.fs.WindowsFileSystemProvider.move(WindowsFileSystemProvider.java:287)
	at java.nio.file.Files.move(Files.java:1395)
	at org.apache.kafka.common.utils.Utils.atomicMoveWithFallback(Utils.java:711)
	at org.apache.kafka.common.record.FileRecords.renameTo(FileRecords.java:210)
	... 10 more
	Suppressed: java.nio.file.FileSystemException: \tmp\kafka-logs\__consumer_offsets-26\00000000000000000000.log.cleaned -> \tmp\kafka-logs\__consumer_offsets-26\00000000000000000000.log.swap: El proceso no tiene acceso al archivo porque está siendo utilizado por otro proceso.

		at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:86)
		at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
		at sun.nio.fs.WindowsFileCopy.move(WindowsFileCopy.java:301)
		at sun.nio.fs.WindowsFileSystemProvider.move(WindowsFileSystemProvider.java:287)
		at java.nio.file.Files.move(Files.java:1395)
		at org.apache.kafka.common.utils.Utils.atomicMoveWithFallback(Utils.java:708)
		... 11 more
[2017-04-02 13:24:10,921] INFO [kafka-log-cleaner-thread-0], Stopped  (kafka.log.LogCleaner)
[2017-04-02 18:04:42,801] INFO Starting the log cleaner (kafka.log.LogCleaner)
[2017-04-02 18:04:42,823] INFO [kafka-log-cleaner-thread-0], Starting  (kafka.log.LogCleaner)
[2017-04-02 18:04:42,862] INFO Cleaner 0: Beginning cleaning of log __consumer_offsets-26. (kafka.log.LogCleaner)
[2017-04-02 18:04:42,863] INFO Cleaner 0: Building offset map for __consumer_offsets-26... (kafka.log.LogCleaner)
[2017-04-02 18:04:42,911] INFO Cleaner 0: Building offset map for log __consumer_offsets-26 for 1 segments in offset range [0, 26). (kafka.log.LogCleaner)
[2017-04-02 18:04:42,951] INFO Cleaner 0: Offset map for log __consumer_offsets-26 complete. (kafka.log.LogCleaner)
[2017-04-02 18:04:42,959] INFO Cleaner 0: Cleaning log __consumer_offsets-26 (cleaning prior to Thu Mar 30 18:10:58 CEST 2017, discarding tombstones prior to Thu Jan 01 01:00:00 CET 1970)... (kafka.log.LogCleaner)
[2017-04-02 18:04:42,975] INFO Cleaner 0: Cleaning segment 0 in log __consumer_offsets-26 (largest timestamp Thu Mar 30 18:10:50 CEST 2017) into 0, retaining deletes. (kafka.log.LogCleaner)
[2017-04-02 18:04:43,037] INFO Cleaner 0: Swapping in cleaned segment 0 for segment(s) 0 in log __consumer_offsets-26. (kafka.log.LogCleaner)
[2017-04-02 18:04:43,060] ERROR [kafka-log-cleaner-thread-0], Error due to  (kafka.log.LogCleaner)
kafka.common.KafkaStorageException: Failed to change the log file suffix from .cleaned to .swap for log segment 0
	at kafka.log.LogSegment.kafkaStorageException$1(LogSegment.scala:340)
	at kafka.log.LogSegment.changeFileSuffixes(LogSegment.scala:342)
	at kafka.log.Log.replaceSegments(Log.scala:1018)
	at kafka.log.Cleaner.cleanSegments(LogCleaner.scala:426)
	at kafka.log.Cleaner$$anonfun$clean$4.apply(LogCleaner.scala:363)
	at kafka.log.Cleaner$$anonfun$clean$4.apply(LogCleaner.scala:362)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at kafka.log.Cleaner.clean(LogCleaner.scala:362)
	at kafka.log.LogCleaner$CleanerThread.cleanOrSleep(LogCleaner.scala:241)
	at kafka.log.LogCleaner$CleanerThread.doWork(LogCleaner.scala:220)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:63)
Caused by: java.nio.file.FileSystemException: \tmp\kafka-logs\__consumer_offsets-26\00000000000000000000.log.cleaned -> \tmp\kafka-logs\__consumer_offsets-26\00000000000000000000.log.swap: El proceso no tiene acceso al archivo porque está siendo utilizado por otro proceso.

	at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:86)
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
	at sun.nio.fs.WindowsFileCopy.move(WindowsFileCopy.java:387)
	at sun.nio.fs.WindowsFileSystemProvider.move(WindowsFileSystemProvider.java:287)
	at java.nio.file.Files.move(Files.java:1395)
	at org.apache.kafka.common.utils.Utils.atomicMoveWithFallback(Utils.java:711)
	at org.apache.kafka.common.record.FileRecords.renameTo(FileRecords.java:210)
	... 10 more
	Suppressed: java.nio.file.FileSystemException: \tmp\kafka-logs\__consumer_offsets-26\00000000000000000000.log.cleaned -> \tmp\kafka-logs\__consumer_offsets-26\00000000000000000000.log.swap: El proceso no tiene acceso al archivo porque está siendo utilizado por otro proceso.

		at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:86)
		at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
		at sun.nio.fs.WindowsFileCopy.move(WindowsFileCopy.java:301)
		at sun.nio.fs.WindowsFileSystemProvider.move(WindowsFileSystemProvider.java:287)
		at java.nio.file.Files.move(Files.java:1395)
		at org.apache.kafka.common.utils.Utils.atomicMoveWithFallback(Utils.java:708)
		... 11 more
[2017-04-02 18:04:43,068] INFO [kafka-log-cleaner-thread-0], Stopped  (kafka.log.LogCleaner)
[2017-04-02 20:20:56,118] INFO Starting the log cleaner (kafka.log.LogCleaner)
[2017-04-02 20:20:56,122] INFO [kafka-log-cleaner-thread-0], Starting  (kafka.log.LogCleaner)
[2017-04-02 20:20:56,144] INFO Cleaner 0: Beginning cleaning of log __consumer_offsets-17. (kafka.log.LogCleaner)
[2017-04-02 20:20:56,144] INFO Cleaner 0: Building offset map for __consumer_offsets-17... (kafka.log.LogCleaner)
[2017-04-02 20:20:56,186] INFO Cleaner 0: Building offset map for log __consumer_offsets-17 for 1 segments in offset range [0, 18). (kafka.log.LogCleaner)
[2017-04-02 20:20:56,197] INFO Cleaner 0: Offset map for log __consumer_offsets-17 complete. (kafka.log.LogCleaner)
[2017-04-02 20:20:56,204] INFO Cleaner 0: Cleaning log __consumer_offsets-17 (cleaning prior to Sun Apr 02 10:49:31 CEST 2017, discarding tombstones prior to Thu Jan 01 01:00:00 CET 1970)... (kafka.log.LogCleaner)
[2017-04-02 20:20:56,208] INFO Cleaner 0: Cleaning segment 0 in log __consumer_offsets-17 (largest timestamp Sun Apr 02 10:49:31 CEST 2017) into 0, retaining deletes. (kafka.log.LogCleaner)
[2017-04-02 20:20:56,258] INFO Cleaner 0: Swapping in cleaned segment 0 for segment(s) 0 in log __consumer_offsets-17. (kafka.log.LogCleaner)
[2017-04-02 20:20:56,276] ERROR [kafka-log-cleaner-thread-0], Error due to  (kafka.log.LogCleaner)
kafka.common.KafkaStorageException: Failed to change the log file suffix from .cleaned to .swap for log segment 0
	at kafka.log.LogSegment.kafkaStorageException$1(LogSegment.scala:340)
	at kafka.log.LogSegment.changeFileSuffixes(LogSegment.scala:342)
	at kafka.log.Log.replaceSegments(Log.scala:1018)
	at kafka.log.Cleaner.cleanSegments(LogCleaner.scala:426)
	at kafka.log.Cleaner$$anonfun$clean$4.apply(LogCleaner.scala:363)
	at kafka.log.Cleaner$$anonfun$clean$4.apply(LogCleaner.scala:362)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at kafka.log.Cleaner.clean(LogCleaner.scala:362)
	at kafka.log.LogCleaner$CleanerThread.cleanOrSleep(LogCleaner.scala:241)
	at kafka.log.LogCleaner$CleanerThread.doWork(LogCleaner.scala:220)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:63)
Caused by: java.nio.file.FileSystemException: \tmp\kafka-logs\__consumer_offsets-17\00000000000000000000.log.cleaned -> \tmp\kafka-logs\__consumer_offsets-17\00000000000000000000.log.swap: El proceso no tiene acceso al archivo porque está siendo utilizado por otro proceso.

	at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:86)
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
	at sun.nio.fs.WindowsFileCopy.move(WindowsFileCopy.java:387)
	at sun.nio.fs.WindowsFileSystemProvider.move(WindowsFileSystemProvider.java:287)
	at java.nio.file.Files.move(Files.java:1395)
	at org.apache.kafka.common.utils.Utils.atomicMoveWithFallback(Utils.java:711)
	at org.apache.kafka.common.record.FileRecords.renameTo(FileRecords.java:210)
	... 10 more
	Suppressed: java.nio.file.FileSystemException: \tmp\kafka-logs\__consumer_offsets-17\00000000000000000000.log.cleaned -> \tmp\kafka-logs\__consumer_offsets-17\00000000000000000000.log.swap: El proceso no tiene acceso al archivo porque está siendo utilizado por otro proceso.

		at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:86)
		at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
		at sun.nio.fs.WindowsFileCopy.move(WindowsFileCopy.java:301)
		at sun.nio.fs.WindowsFileSystemProvider.move(WindowsFileSystemProvider.java:287)
		at java.nio.file.Files.move(Files.java:1395)
		at org.apache.kafka.common.utils.Utils.atomicMoveWithFallback(Utils.java:708)
		... 11 more
[2017-04-02 20:20:56,284] INFO [kafka-log-cleaner-thread-0], Stopped  (kafka.log.LogCleaner)
[2017-04-03 16:28:59,802] INFO Starting the log cleaner (kafka.log.LogCleaner)
[2017-04-03 16:28:59,802] INFO [kafka-log-cleaner-thread-0], Starting  (kafka.log.LogCleaner)
[2017-04-03 16:28:59,833] INFO Cleaner 0: Beginning cleaning of log __consumer_offsets-17. (kafka.log.LogCleaner)
[2017-04-03 16:28:59,833] INFO Cleaner 0: Building offset map for __consumer_offsets-17... (kafka.log.LogCleaner)
[2017-04-03 16:28:59,880] INFO Cleaner 0: Building offset map for log __consumer_offsets-17 for 1 segments in offset range [0, 18). (kafka.log.LogCleaner)
[2017-04-03 16:28:59,880] INFO Cleaner 0: Offset map for log __consumer_offsets-17 complete. (kafka.log.LogCleaner)
[2017-04-03 16:28:59,896] INFO Cleaner 0: Cleaning log __consumer_offsets-17 (cleaning prior to Sun Apr 02 10:49:31 CEST 2017, discarding tombstones prior to Thu Jan 01 01:00:00 CET 1970)... (kafka.log.LogCleaner)
[2017-04-03 16:28:59,896] INFO Cleaner 0: Cleaning segment 0 in log __consumer_offsets-17 (largest timestamp Sun Apr 02 10:49:31 CEST 2017) into 0, retaining deletes. (kafka.log.LogCleaner)
[2017-04-03 16:28:59,958] INFO Cleaner 0: Swapping in cleaned segment 0 for segment(s) 0 in log __consumer_offsets-17. (kafka.log.LogCleaner)
[2017-04-03 16:28:59,974] ERROR [kafka-log-cleaner-thread-0], Error due to  (kafka.log.LogCleaner)
kafka.common.KafkaStorageException: Failed to change the log file suffix from .cleaned to .swap for log segment 0
	at kafka.log.LogSegment.kafkaStorageException$1(LogSegment.scala:340)
	at kafka.log.LogSegment.changeFileSuffixes(LogSegment.scala:342)
	at kafka.log.Log.replaceSegments(Log.scala:1018)
	at kafka.log.Cleaner.cleanSegments(LogCleaner.scala:426)
	at kafka.log.Cleaner$$anonfun$clean$4.apply(LogCleaner.scala:363)
	at kafka.log.Cleaner$$anonfun$clean$4.apply(LogCleaner.scala:362)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at kafka.log.Cleaner.clean(LogCleaner.scala:362)
	at kafka.log.LogCleaner$CleanerThread.cleanOrSleep(LogCleaner.scala:241)
	at kafka.log.LogCleaner$CleanerThread.doWork(LogCleaner.scala:220)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:63)
Caused by: java.nio.file.FileSystemException: \tmp\kafka-logs\__consumer_offsets-17\00000000000000000000.log.cleaned -> \tmp\kafka-logs\__consumer_offsets-17\00000000000000000000.log.swap: El proceso no tiene acceso al archivo porque está siendo utilizado por otro proceso.

	at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:86)
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
	at sun.nio.fs.WindowsFileCopy.move(WindowsFileCopy.java:387)
	at sun.nio.fs.WindowsFileSystemProvider.move(WindowsFileSystemProvider.java:287)
	at java.nio.file.Files.move(Files.java:1395)
	at org.apache.kafka.common.utils.Utils.atomicMoveWithFallback(Utils.java:711)
	at org.apache.kafka.common.record.FileRecords.renameTo(FileRecords.java:210)
	... 10 more
	Suppressed: java.nio.file.FileSystemException: \tmp\kafka-logs\__consumer_offsets-17\00000000000000000000.log.cleaned -> \tmp\kafka-logs\__consumer_offsets-17\00000000000000000000.log.swap: El proceso no tiene acceso al archivo porque está siendo utilizado por otro proceso.

		at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:86)
		at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
		at sun.nio.fs.WindowsFileCopy.move(WindowsFileCopy.java:301)
		at sun.nio.fs.WindowsFileSystemProvider.move(WindowsFileSystemProvider.java:287)
		at java.nio.file.Files.move(Files.java:1395)
		at org.apache.kafka.common.utils.Utils.atomicMoveWithFallback(Utils.java:708)
		... 11 more
[2017-04-03 16:28:59,974] INFO [kafka-log-cleaner-thread-0], Stopped  (kafka.log.LogCleaner)
[2017-04-03 21:48:41,463] INFO Starting the log cleaner (kafka.log.LogCleaner)
[2017-04-03 21:48:41,467] INFO [kafka-log-cleaner-thread-0], Starting  (kafka.log.LogCleaner)
[2017-04-03 21:48:41,505] INFO Cleaner 0: Beginning cleaning of log __consumer_offsets-42. (kafka.log.LogCleaner)
[2017-04-03 21:48:41,506] INFO Cleaner 0: Building offset map for __consumer_offsets-42... (kafka.log.LogCleaner)
[2017-04-03 21:48:41,563] INFO Cleaner 0: Building offset map for log __consumer_offsets-42 for 1 segments in offset range [0, 10). (kafka.log.LogCleaner)
[2017-04-03 21:48:41,577] INFO Cleaner 0: Offset map for log __consumer_offsets-42 complete. (kafka.log.LogCleaner)
[2017-04-03 21:48:41,583] INFO Cleaner 0: Cleaning log __consumer_offsets-42 (cleaning prior to Sun Apr 02 13:11:40 CEST 2017, discarding tombstones prior to Thu Jan 01 01:00:00 CET 1970)... (kafka.log.LogCleaner)
[2017-04-03 21:48:41,590] INFO Cleaner 0: Cleaning segment 0 in log __consumer_offsets-42 (largest timestamp Sun Apr 02 13:11:39 CEST 2017) into 0, retaining deletes. (kafka.log.LogCleaner)
[2017-04-03 21:48:41,645] INFO Cleaner 0: Swapping in cleaned segment 0 for segment(s) 0 in log __consumer_offsets-42. (kafka.log.LogCleaner)
[2017-04-03 21:48:41,665] ERROR [kafka-log-cleaner-thread-0], Error due to  (kafka.log.LogCleaner)
kafka.common.KafkaStorageException: Failed to change the log file suffix from .cleaned to .swap for log segment 0
	at kafka.log.LogSegment.kafkaStorageException$1(LogSegment.scala:340)
	at kafka.log.LogSegment.changeFileSuffixes(LogSegment.scala:342)
	at kafka.log.Log.replaceSegments(Log.scala:1018)
	at kafka.log.Cleaner.cleanSegments(LogCleaner.scala:426)
	at kafka.log.Cleaner$$anonfun$clean$4.apply(LogCleaner.scala:363)
	at kafka.log.Cleaner$$anonfun$clean$4.apply(LogCleaner.scala:362)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at kafka.log.Cleaner.clean(LogCleaner.scala:362)
	at kafka.log.LogCleaner$CleanerThread.cleanOrSleep(LogCleaner.scala:241)
	at kafka.log.LogCleaner$CleanerThread.doWork(LogCleaner.scala:220)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:63)
Caused by: java.nio.file.FileSystemException: \tmp\kafka-logs\__consumer_offsets-42\00000000000000000000.log.cleaned -> \tmp\kafka-logs\__consumer_offsets-42\00000000000000000000.log.swap: El proceso no tiene acceso al archivo porque está siendo utilizado por otro proceso.

	at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:86)
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
	at sun.nio.fs.WindowsFileCopy.move(WindowsFileCopy.java:387)
	at sun.nio.fs.WindowsFileSystemProvider.move(WindowsFileSystemProvider.java:287)
	at java.nio.file.Files.move(Files.java:1395)
	at org.apache.kafka.common.utils.Utils.atomicMoveWithFallback(Utils.java:711)
	at org.apache.kafka.common.record.FileRecords.renameTo(FileRecords.java:210)
	... 10 more
	Suppressed: java.nio.file.FileSystemException: \tmp\kafka-logs\__consumer_offsets-42\00000000000000000000.log.cleaned -> \tmp\kafka-logs\__consumer_offsets-42\00000000000000000000.log.swap: El proceso no tiene acceso al archivo porque está siendo utilizado por otro proceso.

		at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:86)
		at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
		at sun.nio.fs.WindowsFileCopy.move(WindowsFileCopy.java:301)
		at sun.nio.fs.WindowsFileSystemProvider.move(WindowsFileSystemProvider.java:287)
		at java.nio.file.Files.move(Files.java:1395)
		at org.apache.kafka.common.utils.Utils.atomicMoveWithFallback(Utils.java:708)
		... 11 more
[2017-04-03 21:48:41,672] INFO [kafka-log-cleaner-thread-0], Stopped  (kafka.log.LogCleaner)
[2017-04-03 22:38:22,111] INFO Starting the log cleaner (kafka.log.LogCleaner)
[2017-04-03 22:38:22,118] INFO [kafka-log-cleaner-thread-0], Starting  (kafka.log.LogCleaner)
[2017-04-03 22:38:22,158] INFO Cleaner 0: Beginning cleaning of log __consumer_offsets-42. (kafka.log.LogCleaner)
[2017-04-03 22:38:22,158] INFO Cleaner 0: Building offset map for __consumer_offsets-42... (kafka.log.LogCleaner)
[2017-04-03 22:38:22,206] INFO Cleaner 0: Building offset map for log __consumer_offsets-42 for 1 segments in offset range [0, 10). (kafka.log.LogCleaner)
[2017-04-03 22:38:22,217] INFO Cleaner 0: Offset map for log __consumer_offsets-42 complete. (kafka.log.LogCleaner)
[2017-04-03 22:38:22,223] INFO Cleaner 0: Cleaning log __consumer_offsets-42 (cleaning prior to Sun Apr 02 13:11:40 CEST 2017, discarding tombstones prior to Thu Jan 01 01:00:00 CET 1970)... (kafka.log.LogCleaner)
[2017-04-03 22:38:22,230] INFO Cleaner 0: Cleaning segment 0 in log __consumer_offsets-42 (largest timestamp Sun Apr 02 13:11:39 CEST 2017) into 0, retaining deletes. (kafka.log.LogCleaner)
[2017-04-03 22:38:22,279] INFO Cleaner 0: Swapping in cleaned segment 0 for segment(s) 0 in log __consumer_offsets-42. (kafka.log.LogCleaner)
[2017-04-03 22:38:22,308] ERROR [kafka-log-cleaner-thread-0], Error due to  (kafka.log.LogCleaner)
kafka.common.KafkaStorageException: Failed to change the log file suffix from .cleaned to .swap for log segment 0
	at kafka.log.LogSegment.kafkaStorageException$1(LogSegment.scala:340)
	at kafka.log.LogSegment.changeFileSuffixes(LogSegment.scala:342)
	at kafka.log.Log.replaceSegments(Log.scala:1018)
	at kafka.log.Cleaner.cleanSegments(LogCleaner.scala:426)
	at kafka.log.Cleaner$$anonfun$clean$4.apply(LogCleaner.scala:363)
	at kafka.log.Cleaner$$anonfun$clean$4.apply(LogCleaner.scala:362)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at kafka.log.Cleaner.clean(LogCleaner.scala:362)
	at kafka.log.LogCleaner$CleanerThread.cleanOrSleep(LogCleaner.scala:241)
	at kafka.log.LogCleaner$CleanerThread.doWork(LogCleaner.scala:220)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:63)
Caused by: java.nio.file.FileSystemException: \tmp\kafka-logs\__consumer_offsets-42\00000000000000000000.log.cleaned -> \tmp\kafka-logs\__consumer_offsets-42\00000000000000000000.log.swap: El proceso no tiene acceso al archivo porque está siendo utilizado por otro proceso.

	at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:86)
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
	at sun.nio.fs.WindowsFileCopy.move(WindowsFileCopy.java:387)
	at sun.nio.fs.WindowsFileSystemProvider.move(WindowsFileSystemProvider.java:287)
	at java.nio.file.Files.move(Files.java:1395)
	at org.apache.kafka.common.utils.Utils.atomicMoveWithFallback(Utils.java:711)
	at org.apache.kafka.common.record.FileRecords.renameTo(FileRecords.java:210)
	... 10 more
	Suppressed: java.nio.file.FileSystemException: \tmp\kafka-logs\__consumer_offsets-42\00000000000000000000.log.cleaned -> \tmp\kafka-logs\__consumer_offsets-42\00000000000000000000.log.swap: El proceso no tiene acceso al archivo porque está siendo utilizado por otro proceso.

		at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:86)
		at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
		at sun.nio.fs.WindowsFileCopy.move(WindowsFileCopy.java:301)
		at sun.nio.fs.WindowsFileSystemProvider.move(WindowsFileSystemProvider.java:287)
		at java.nio.file.Files.move(Files.java:1395)
		at org.apache.kafka.common.utils.Utils.atomicMoveWithFallback(Utils.java:708)
		... 11 more
[2017-04-03 22:38:22,314] INFO [kafka-log-cleaner-thread-0], Stopped  (kafka.log.LogCleaner)
[2017-04-04 09:58:16,180] INFO Starting the log cleaner (kafka.log.LogCleaner)
[2017-04-04 09:58:16,183] INFO [kafka-log-cleaner-thread-0], Starting  (kafka.log.LogCleaner)
[2017-04-04 09:58:16,213] INFO Cleaner 0: Beginning cleaning of log __consumer_offsets-42. (kafka.log.LogCleaner)
[2017-04-04 09:58:16,214] INFO Cleaner 0: Building offset map for __consumer_offsets-42... (kafka.log.LogCleaner)
[2017-04-04 09:58:16,253] INFO Cleaner 0: Building offset map for log __consumer_offsets-42 for 1 segments in offset range [0, 10). (kafka.log.LogCleaner)
[2017-04-04 09:58:16,264] INFO Cleaner 0: Offset map for log __consumer_offsets-42 complete. (kafka.log.LogCleaner)
[2017-04-04 09:58:16,271] INFO Cleaner 0: Cleaning log __consumer_offsets-42 (cleaning prior to Sun Apr 02 13:11:40 CEST 2017, discarding tombstones prior to Thu Jan 01 01:00:00 CET 1970)... (kafka.log.LogCleaner)
[2017-04-04 09:58:16,276] INFO Cleaner 0: Cleaning segment 0 in log __consumer_offsets-42 (largest timestamp Sun Apr 02 13:11:39 CEST 2017) into 0, retaining deletes. (kafka.log.LogCleaner)
[2017-04-04 09:58:16,320] INFO Cleaner 0: Swapping in cleaned segment 0 for segment(s) 0 in log __consumer_offsets-42. (kafka.log.LogCleaner)
[2017-04-04 09:58:16,334] ERROR [kafka-log-cleaner-thread-0], Error due to  (kafka.log.LogCleaner)
kafka.common.KafkaStorageException: Failed to change the log file suffix from .cleaned to .swap for log segment 0
	at kafka.log.LogSegment.kafkaStorageException$1(LogSegment.scala:340)
	at kafka.log.LogSegment.changeFileSuffixes(LogSegment.scala:342)
	at kafka.log.Log.replaceSegments(Log.scala:1018)
	at kafka.log.Cleaner.cleanSegments(LogCleaner.scala:426)
	at kafka.log.Cleaner$$anonfun$clean$4.apply(LogCleaner.scala:363)
	at kafka.log.Cleaner$$anonfun$clean$4.apply(LogCleaner.scala:362)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at kafka.log.Cleaner.clean(LogCleaner.scala:362)
	at kafka.log.LogCleaner$CleanerThread.cleanOrSleep(LogCleaner.scala:241)
	at kafka.log.LogCleaner$CleanerThread.doWork(LogCleaner.scala:220)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:63)
Caused by: java.nio.file.FileSystemException: \tmp\kafka-logs\__consumer_offsets-42\00000000000000000000.log.cleaned -> \tmp\kafka-logs\__consumer_offsets-42\00000000000000000000.log.swap: El proceso no tiene acceso al archivo porque está siendo utilizado por otro proceso.

	at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:86)
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
	at sun.nio.fs.WindowsFileCopy.move(WindowsFileCopy.java:387)
	at sun.nio.fs.WindowsFileSystemProvider.move(WindowsFileSystemProvider.java:287)
	at java.nio.file.Files.move(Files.java:1395)
	at org.apache.kafka.common.utils.Utils.atomicMoveWithFallback(Utils.java:711)
	at org.apache.kafka.common.record.FileRecords.renameTo(FileRecords.java:210)
	... 10 more
	Suppressed: java.nio.file.FileSystemException: \tmp\kafka-logs\__consumer_offsets-42\00000000000000000000.log.cleaned -> \tmp\kafka-logs\__consumer_offsets-42\00000000000000000000.log.swap: El proceso no tiene acceso al archivo porque está siendo utilizado por otro proceso.

		at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:86)
		at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
		at sun.nio.fs.WindowsFileCopy.move(WindowsFileCopy.java:301)
		at sun.nio.fs.WindowsFileSystemProvider.move(WindowsFileSystemProvider.java:287)
		at java.nio.file.Files.move(Files.java:1395)
		at org.apache.kafka.common.utils.Utils.atomicMoveWithFallback(Utils.java:708)
		... 11 more
[2017-04-04 09:58:16,339] INFO [kafka-log-cleaner-thread-0], Stopped  (kafka.log.LogCleaner)
[2017-04-04 09:58:18,812] INFO Shutting down the log cleaner. (kafka.log.LogCleaner)
[2017-04-04 09:58:18,813] INFO [kafka-log-cleaner-thread-0], Shutting down (kafka.log.LogCleaner)
[2017-04-04 09:58:18,813] INFO [kafka-log-cleaner-thread-0], Shutdown completed (kafka.log.LogCleaner)
[2017-04-04 09:59:38,063] INFO Starting the log cleaner (kafka.log.LogCleaner)
[2017-04-04 09:59:38,071] INFO [kafka-log-cleaner-thread-0], Starting  (kafka.log.LogCleaner)
[2017-04-04 09:59:38,102] INFO Cleaner 0: Beginning cleaning of log __consumer_offsets-42. (kafka.log.LogCleaner)
[2017-04-04 09:59:38,103] INFO Cleaner 0: Building offset map for __consumer_offsets-42... (kafka.log.LogCleaner)
[2017-04-04 09:59:38,146] INFO Cleaner 0: Building offset map for log __consumer_offsets-42 for 1 segments in offset range [0, 10). (kafka.log.LogCleaner)
[2017-04-04 09:59:38,157] INFO Cleaner 0: Offset map for log __consumer_offsets-42 complete. (kafka.log.LogCleaner)
[2017-04-04 09:59:38,163] INFO Cleaner 0: Cleaning log __consumer_offsets-42 (cleaning prior to Sun Apr 02 13:11:40 CEST 2017, discarding tombstones prior to Thu Jan 01 01:00:00 CET 1970)... (kafka.log.LogCleaner)
[2017-04-04 09:59:38,167] INFO Cleaner 0: Cleaning segment 0 in log __consumer_offsets-42 (largest timestamp Sun Apr 02 13:11:39 CEST 2017) into 0, retaining deletes. (kafka.log.LogCleaner)
[2017-04-04 09:59:38,210] INFO Cleaner 0: Swapping in cleaned segment 0 for segment(s) 0 in log __consumer_offsets-42. (kafka.log.LogCleaner)
[2017-04-04 09:59:38,224] ERROR [kafka-log-cleaner-thread-0], Error due to  (kafka.log.LogCleaner)
kafka.common.KafkaStorageException: Failed to change the log file suffix from .cleaned to .swap for log segment 0
	at kafka.log.LogSegment.kafkaStorageException$1(LogSegment.scala:340)
	at kafka.log.LogSegment.changeFileSuffixes(LogSegment.scala:342)
	at kafka.log.Log.replaceSegments(Log.scala:1018)
	at kafka.log.Cleaner.cleanSegments(LogCleaner.scala:426)
	at kafka.log.Cleaner$$anonfun$clean$4.apply(LogCleaner.scala:363)
	at kafka.log.Cleaner$$anonfun$clean$4.apply(LogCleaner.scala:362)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at kafka.log.Cleaner.clean(LogCleaner.scala:362)
	at kafka.log.LogCleaner$CleanerThread.cleanOrSleep(LogCleaner.scala:241)
	at kafka.log.LogCleaner$CleanerThread.doWork(LogCleaner.scala:220)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:63)
Caused by: java.nio.file.FileSystemException: \tmp\kafka-logs\__consumer_offsets-42\00000000000000000000.log.cleaned -> \tmp\kafka-logs\__consumer_offsets-42\00000000000000000000.log.swap: El proceso no tiene acceso al archivo porque está siendo utilizado por otro proceso.

	at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:86)
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
	at sun.nio.fs.WindowsFileCopy.move(WindowsFileCopy.java:387)
	at sun.nio.fs.WindowsFileSystemProvider.move(WindowsFileSystemProvider.java:287)
	at java.nio.file.Files.move(Files.java:1395)
	at org.apache.kafka.common.utils.Utils.atomicMoveWithFallback(Utils.java:711)
	at org.apache.kafka.common.record.FileRecords.renameTo(FileRecords.java:210)
	... 10 more
	Suppressed: java.nio.file.FileSystemException: \tmp\kafka-logs\__consumer_offsets-42\00000000000000000000.log.cleaned -> \tmp\kafka-logs\__consumer_offsets-42\00000000000000000000.log.swap: El proceso no tiene acceso al archivo porque está siendo utilizado por otro proceso.

		at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:86)
		at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
		at sun.nio.fs.WindowsFileCopy.move(WindowsFileCopy.java:301)
		at sun.nio.fs.WindowsFileSystemProvider.move(WindowsFileSystemProvider.java:287)
		at java.nio.file.Files.move(Files.java:1395)
		at org.apache.kafka.common.utils.Utils.atomicMoveWithFallback(Utils.java:708)
		... 11 more
[2017-04-04 09:59:38,228] INFO [kafka-log-cleaner-thread-0], Stopped  (kafka.log.LogCleaner)
[2017-04-04 10:20:38,448] INFO Starting the log cleaner (kafka.log.LogCleaner)
[2017-04-04 10:20:38,463] INFO [kafka-log-cleaner-thread-0], Starting  (kafka.log.LogCleaner)
[2017-04-04 10:20:38,479] INFO Cleaner 0: Beginning cleaning of log __consumer_offsets-42. (kafka.log.LogCleaner)
[2017-04-04 10:20:38,479] INFO Cleaner 0: Building offset map for __consumer_offsets-42... (kafka.log.LogCleaner)
[2017-04-04 10:20:38,526] INFO Cleaner 0: Building offset map for log __consumer_offsets-42 for 1 segments in offset range [0, 10). (kafka.log.LogCleaner)
[2017-04-04 10:20:38,526] INFO Cleaner 0: Offset map for log __consumer_offsets-42 complete. (kafka.log.LogCleaner)
[2017-04-04 10:20:38,541] INFO Cleaner 0: Cleaning log __consumer_offsets-42 (cleaning prior to Sun Apr 02 13:11:40 CEST 2017, discarding tombstones prior to Thu Jan 01 01:00:00 CET 1970)... (kafka.log.LogCleaner)
[2017-04-04 10:20:38,541] INFO Cleaner 0: Cleaning segment 0 in log __consumer_offsets-42 (largest timestamp Sun Apr 02 13:11:39 CEST 2017) into 0, retaining deletes. (kafka.log.LogCleaner)
[2017-04-04 10:20:38,588] INFO Cleaner 0: Swapping in cleaned segment 0 for segment(s) 0 in log __consumer_offsets-42. (kafka.log.LogCleaner)
[2017-04-04 10:20:38,604] ERROR [kafka-log-cleaner-thread-0], Error due to  (kafka.log.LogCleaner)
kafka.common.KafkaStorageException: Failed to change the log file suffix from .cleaned to .swap for log segment 0
	at kafka.log.LogSegment.kafkaStorageException$1(LogSegment.scala:340)
	at kafka.log.LogSegment.changeFileSuffixes(LogSegment.scala:342)
	at kafka.log.Log.replaceSegments(Log.scala:1018)
	at kafka.log.Cleaner.cleanSegments(LogCleaner.scala:426)
	at kafka.log.Cleaner$$anonfun$clean$4.apply(LogCleaner.scala:363)
	at kafka.log.Cleaner$$anonfun$clean$4.apply(LogCleaner.scala:362)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at kafka.log.Cleaner.clean(LogCleaner.scala:362)
	at kafka.log.LogCleaner$CleanerThread.cleanOrSleep(LogCleaner.scala:241)
	at kafka.log.LogCleaner$CleanerThread.doWork(LogCleaner.scala:220)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:63)
Caused by: java.nio.file.FileSystemException: \tmp\kafka-logs\__consumer_offsets-42\00000000000000000000.log.cleaned -> \tmp\kafka-logs\__consumer_offsets-42\00000000000000000000.log.swap: El proceso no tiene acceso al archivo porque está siendo utilizado por otro proceso.

	at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:86)
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
	at sun.nio.fs.WindowsFileCopy.move(WindowsFileCopy.java:387)
	at sun.nio.fs.WindowsFileSystemProvider.move(WindowsFileSystemProvider.java:287)
	at java.nio.file.Files.move(Files.java:1395)
	at org.apache.kafka.common.utils.Utils.atomicMoveWithFallback(Utils.java:711)
	at org.apache.kafka.common.record.FileRecords.renameTo(FileRecords.java:210)
	... 10 more
	Suppressed: java.nio.file.FileSystemException: \tmp\kafka-logs\__consumer_offsets-42\00000000000000000000.log.cleaned -> \tmp\kafka-logs\__consumer_offsets-42\00000000000000000000.log.swap: El proceso no tiene acceso al archivo porque está siendo utilizado por otro proceso.

		at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:86)
		at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
		at sun.nio.fs.WindowsFileCopy.move(WindowsFileCopy.java:301)
		at sun.nio.fs.WindowsFileSystemProvider.move(WindowsFileSystemProvider.java:287)
		at java.nio.file.Files.move(Files.java:1395)
		at org.apache.kafka.common.utils.Utils.atomicMoveWithFallback(Utils.java:708)
		... 11 more
[2017-04-04 10:20:38,620] INFO [kafka-log-cleaner-thread-0], Stopped  (kafka.log.LogCleaner)
[2017-04-04 10:20:41,300] INFO Shutting down the log cleaner. (kafka.log.LogCleaner)
[2017-04-04 10:20:41,300] INFO [kafka-log-cleaner-thread-0], Shutting down (kafka.log.LogCleaner)
[2017-04-04 10:20:41,300] INFO [kafka-log-cleaner-thread-0], Shutdown completed (kafka.log.LogCleaner)
[2017-04-04 10:20:58,632] INFO Starting the log cleaner (kafka.log.LogCleaner)
[2017-04-04 10:20:58,632] INFO [kafka-log-cleaner-thread-0], Starting  (kafka.log.LogCleaner)
[2017-04-04 10:20:58,663] INFO Cleaner 0: Beginning cleaning of log __consumer_offsets-42. (kafka.log.LogCleaner)
[2017-04-04 10:20:58,663] INFO Cleaner 0: Building offset map for __consumer_offsets-42... (kafka.log.LogCleaner)
[2017-04-04 10:20:58,710] INFO Cleaner 0: Building offset map for log __consumer_offsets-42 for 1 segments in offset range [0, 10). (kafka.log.LogCleaner)
[2017-04-04 10:20:58,741] INFO Cleaner 0: Offset map for log __consumer_offsets-42 complete. (kafka.log.LogCleaner)
[2017-04-04 10:20:58,741] INFO Cleaner 0: Cleaning log __consumer_offsets-42 (cleaning prior to Sun Apr 02 13:11:40 CEST 2017, discarding tombstones prior to Thu Jan 01 01:00:00 CET 1970)... (kafka.log.LogCleaner)
[2017-04-04 10:20:58,757] INFO Cleaner 0: Cleaning segment 0 in log __consumer_offsets-42 (largest timestamp Sun Apr 02 13:11:39 CEST 2017) into 0, retaining deletes. (kafka.log.LogCleaner)
[2017-04-04 10:20:58,835] INFO Cleaner 0: Swapping in cleaned segment 0 for segment(s) 0 in log __consumer_offsets-42. (kafka.log.LogCleaner)
[2017-04-04 10:20:58,850] ERROR [kafka-log-cleaner-thread-0], Error due to  (kafka.log.LogCleaner)
kafka.common.KafkaStorageException: Failed to change the log file suffix from .cleaned to .swap for log segment 0
	at kafka.log.LogSegment.kafkaStorageException$1(LogSegment.scala:340)
	at kafka.log.LogSegment.changeFileSuffixes(LogSegment.scala:342)
	at kafka.log.Log.replaceSegments(Log.scala:1018)
	at kafka.log.Cleaner.cleanSegments(LogCleaner.scala:426)
	at kafka.log.Cleaner$$anonfun$clean$4.apply(LogCleaner.scala:363)
	at kafka.log.Cleaner$$anonfun$clean$4.apply(LogCleaner.scala:362)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at kafka.log.Cleaner.clean(LogCleaner.scala:362)
	at kafka.log.LogCleaner$CleanerThread.cleanOrSleep(LogCleaner.scala:241)
	at kafka.log.LogCleaner$CleanerThread.doWork(LogCleaner.scala:220)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:63)
Caused by: java.nio.file.FileSystemException: \tmp\kafka-logs\__consumer_offsets-42\00000000000000000000.log.cleaned -> \tmp\kafka-logs\__consumer_offsets-42\00000000000000000000.log.swap: El proceso no tiene acceso al archivo porque está siendo utilizado por otro proceso.

	at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:86)
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
	at sun.nio.fs.WindowsFileCopy.move(WindowsFileCopy.java:387)
	at sun.nio.fs.WindowsFileSystemProvider.move(WindowsFileSystemProvider.java:287)
	at java.nio.file.Files.move(Files.java:1395)
	at org.apache.kafka.common.utils.Utils.atomicMoveWithFallback(Utils.java:711)
	at org.apache.kafka.common.record.FileRecords.renameTo(FileRecords.java:210)
	... 10 more
	Suppressed: java.nio.file.FileSystemException: \tmp\kafka-logs\__consumer_offsets-42\00000000000000000000.log.cleaned -> \tmp\kafka-logs\__consumer_offsets-42\00000000000000000000.log.swap: El proceso no tiene acceso al archivo porque está siendo utilizado por otro proceso.

		at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:86)
		at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
		at sun.nio.fs.WindowsFileCopy.move(WindowsFileCopy.java:301)
		at sun.nio.fs.WindowsFileSystemProvider.move(WindowsFileSystemProvider.java:287)
		at java.nio.file.Files.move(Files.java:1395)
		at org.apache.kafka.common.utils.Utils.atomicMoveWithFallback(Utils.java:708)
		... 11 more
[2017-04-04 10:20:58,850] INFO [kafka-log-cleaner-thread-0], Stopped  (kafka.log.LogCleaner)
[2017-04-04 19:21:31,143] INFO Starting the log cleaner (kafka.log.LogCleaner)
[2017-04-04 19:21:31,151] INFO [kafka-log-cleaner-thread-0], Starting  (kafka.log.LogCleaner)
[2017-04-04 19:21:31,268] INFO Cleaner 0: Beginning cleaning of log __consumer_offsets-42. (kafka.log.LogCleaner)
[2017-04-04 19:21:31,269] INFO Cleaner 0: Building offset map for __consumer_offsets-42... (kafka.log.LogCleaner)
[2017-04-04 19:21:31,316] INFO Cleaner 0: Building offset map for log __consumer_offsets-42 for 1 segments in offset range [0, 10). (kafka.log.LogCleaner)
[2017-04-04 19:21:31,336] INFO Cleaner 0: Offset map for log __consumer_offsets-42 complete. (kafka.log.LogCleaner)
[2017-04-04 19:21:31,354] INFO Cleaner 0: Cleaning log __consumer_offsets-42 (cleaning prior to Sun Apr 02 13:11:40 CEST 2017, discarding tombstones prior to Thu Jan 01 01:00:00 CET 1970)... (kafka.log.LogCleaner)
[2017-04-04 19:21:31,360] INFO Cleaner 0: Cleaning segment 0 in log __consumer_offsets-42 (largest timestamp Sun Apr 02 13:11:39 CEST 2017) into 0, retaining deletes. (kafka.log.LogCleaner)
[2017-04-04 19:21:31,480] INFO Cleaner 0: Swapping in cleaned segment 0 for segment(s) 0 in log __consumer_offsets-42. (kafka.log.LogCleaner)
[2017-04-04 19:21:31,545] ERROR [kafka-log-cleaner-thread-0], Error due to  (kafka.log.LogCleaner)
kafka.common.KafkaStorageException: Failed to change the log file suffix from .cleaned to .swap for log segment 0
	at kafka.log.LogSegment.kafkaStorageException$1(LogSegment.scala:340)
	at kafka.log.LogSegment.changeFileSuffixes(LogSegment.scala:342)
	at kafka.log.Log.replaceSegments(Log.scala:1018)
	at kafka.log.Cleaner.cleanSegments(LogCleaner.scala:426)
	at kafka.log.Cleaner$$anonfun$clean$4.apply(LogCleaner.scala:363)
	at kafka.log.Cleaner$$anonfun$clean$4.apply(LogCleaner.scala:362)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at kafka.log.Cleaner.clean(LogCleaner.scala:362)
	at kafka.log.LogCleaner$CleanerThread.cleanOrSleep(LogCleaner.scala:241)
	at kafka.log.LogCleaner$CleanerThread.doWork(LogCleaner.scala:220)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:63)
Caused by: java.nio.file.FileSystemException: \tmp\kafka-logs\__consumer_offsets-42\00000000000000000000.log.cleaned -> \tmp\kafka-logs\__consumer_offsets-42\00000000000000000000.log.swap: El proceso no tiene acceso al archivo porque está siendo utilizado por otro proceso.

	at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:86)
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
	at sun.nio.fs.WindowsFileCopy.move(WindowsFileCopy.java:387)
	at sun.nio.fs.WindowsFileSystemProvider.move(WindowsFileSystemProvider.java:287)
	at java.nio.file.Files.move(Files.java:1395)
	at org.apache.kafka.common.utils.Utils.atomicMoveWithFallback(Utils.java:711)
	at org.apache.kafka.common.record.FileRecords.renameTo(FileRecords.java:210)
	... 10 more
	Suppressed: java.nio.file.FileSystemException: \tmp\kafka-logs\__consumer_offsets-42\00000000000000000000.log.cleaned -> \tmp\kafka-logs\__consumer_offsets-42\00000000000000000000.log.swap: El proceso no tiene acceso al archivo porque está siendo utilizado por otro proceso.

		at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:86)
		at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
		at sun.nio.fs.WindowsFileCopy.move(WindowsFileCopy.java:301)
		at sun.nio.fs.WindowsFileSystemProvider.move(WindowsFileSystemProvider.java:287)
		at java.nio.file.Files.move(Files.java:1395)
		at org.apache.kafka.common.utils.Utils.atomicMoveWithFallback(Utils.java:708)
		... 11 more
[2017-04-04 19:21:31,562] INFO [kafka-log-cleaner-thread-0], Stopped  (kafka.log.LogCleaner)
[2017-04-09 17:16:13,133] INFO Starting the log cleaner (kafka.log.LogCleaner)
[2017-04-09 17:16:13,141] INFO [kafka-log-cleaner-thread-0], Starting  (kafka.log.LogCleaner)
[2017-04-09 17:16:13,216] INFO Cleaner 0: Beginning cleaning of log __consumer_offsets-42. (kafka.log.LogCleaner)
[2017-04-09 17:16:13,217] INFO Cleaner 0: Building offset map for __consumer_offsets-42... (kafka.log.LogCleaner)
[2017-04-09 17:16:13,296] INFO Cleaner 0: Building offset map for log __consumer_offsets-42 for 1 segments in offset range [0, 10). (kafka.log.LogCleaner)
[2017-04-09 17:16:13,325] INFO Cleaner 0: Offset map for log __consumer_offsets-42 complete. (kafka.log.LogCleaner)
[2017-04-09 17:16:13,332] INFO Cleaner 0: Cleaning log __consumer_offsets-42 (cleaning prior to Sun Apr 02 13:11:40 CEST 2017, discarding tombstones prior to Thu Jan 01 01:00:00 CET 1970)... (kafka.log.LogCleaner)
[2017-04-09 17:16:13,339] INFO Cleaner 0: Cleaning segment 0 in log __consumer_offsets-42 (largest timestamp Sun Apr 02 13:11:39 CEST 2017) into 0, retaining deletes. (kafka.log.LogCleaner)
[2017-04-09 17:16:13,415] INFO Cleaner 0: Swapping in cleaned segment 0 for segment(s) 0 in log __consumer_offsets-42. (kafka.log.LogCleaner)
[2017-04-09 17:16:13,433] ERROR [kafka-log-cleaner-thread-0], Error due to  (kafka.log.LogCleaner)
kafka.common.KafkaStorageException: Failed to change the log file suffix from .cleaned to .swap for log segment 0
	at kafka.log.LogSegment.kafkaStorageException$1(LogSegment.scala:340)
	at kafka.log.LogSegment.changeFileSuffixes(LogSegment.scala:342)
	at kafka.log.Log.replaceSegments(Log.scala:1018)
	at kafka.log.Cleaner.cleanSegments(LogCleaner.scala:426)
	at kafka.log.Cleaner$$anonfun$clean$4.apply(LogCleaner.scala:363)
	at kafka.log.Cleaner$$anonfun$clean$4.apply(LogCleaner.scala:362)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at kafka.log.Cleaner.clean(LogCleaner.scala:362)
	at kafka.log.LogCleaner$CleanerThread.cleanOrSleep(LogCleaner.scala:241)
	at kafka.log.LogCleaner$CleanerThread.doWork(LogCleaner.scala:220)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:63)
Caused by: java.nio.file.FileSystemException: \tmp\kafka-logs\__consumer_offsets-42\00000000000000000000.log.cleaned -> \tmp\kafka-logs\__consumer_offsets-42\00000000000000000000.log.swap: El proceso no tiene acceso al archivo porque está siendo utilizado por otro proceso.

	at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:86)
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
	at sun.nio.fs.WindowsFileCopy.move(WindowsFileCopy.java:387)
	at sun.nio.fs.WindowsFileSystemProvider.move(WindowsFileSystemProvider.java:287)
	at java.nio.file.Files.move(Files.java:1395)
	at org.apache.kafka.common.utils.Utils.atomicMoveWithFallback(Utils.java:711)
	at org.apache.kafka.common.record.FileRecords.renameTo(FileRecords.java:210)
	... 10 more
	Suppressed: java.nio.file.FileSystemException: \tmp\kafka-logs\__consumer_offsets-42\00000000000000000000.log.cleaned -> \tmp\kafka-logs\__consumer_offsets-42\00000000000000000000.log.swap: El proceso no tiene acceso al archivo porque está siendo utilizado por otro proceso.

		at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:86)
		at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
		at sun.nio.fs.WindowsFileCopy.move(WindowsFileCopy.java:301)
		at sun.nio.fs.WindowsFileSystemProvider.move(WindowsFileSystemProvider.java:287)
		at java.nio.file.Files.move(Files.java:1395)
		at org.apache.kafka.common.utils.Utils.atomicMoveWithFallback(Utils.java:708)
		... 11 more
[2017-04-09 17:16:13,440] INFO [kafka-log-cleaner-thread-0], Stopped  (kafka.log.LogCleaner)
[2017-04-09 17:33:18,734] INFO Starting the log cleaner (kafka.log.LogCleaner)
[2017-04-09 17:33:18,736] INFO [kafka-log-cleaner-thread-0], Starting  (kafka.log.LogCleaner)
[2017-04-09 17:33:18,769] INFO Cleaner 0: Beginning cleaning of log __consumer_offsets-46. (kafka.log.LogCleaner)
[2017-04-09 17:33:18,769] INFO Cleaner 0: Building offset map for __consumer_offsets-46... (kafka.log.LogCleaner)
[2017-04-09 17:33:18,824] INFO Cleaner 0: Building offset map for log __consumer_offsets-46 for 1 segments in offset range [0, 23). (kafka.log.LogCleaner)
[2017-04-09 17:33:18,840] INFO Cleaner 0: Offset map for log __consumer_offsets-46 complete. (kafka.log.LogCleaner)
[2017-04-09 17:33:18,848] INFO Cleaner 0: Cleaning log __consumer_offsets-46 (cleaning prior to Tue Apr 04 10:26:04 CEST 2017, discarding tombstones prior to Thu Jan 01 01:00:00 CET 1970)... (kafka.log.LogCleaner)
[2017-04-09 17:33:18,853] INFO Cleaner 0: Cleaning segment 0 in log __consumer_offsets-46 (largest timestamp Tue Apr 04 10:25:50 CEST 2017) into 0, retaining deletes. (kafka.log.LogCleaner)
[2017-04-09 17:33:19,000] INFO Cleaner 0: Swapping in cleaned segment 0 for segment(s) 0 in log __consumer_offsets-46. (kafka.log.LogCleaner)
[2017-04-09 17:33:19,141] ERROR [kafka-log-cleaner-thread-0], Error due to  (kafka.log.LogCleaner)
kafka.common.KafkaStorageException: Failed to change the log file suffix from .cleaned to .swap for log segment 0
	at kafka.log.LogSegment.kafkaStorageException$1(LogSegment.scala:340)
	at kafka.log.LogSegment.changeFileSuffixes(LogSegment.scala:342)
	at kafka.log.Log.replaceSegments(Log.scala:1018)
	at kafka.log.Cleaner.cleanSegments(LogCleaner.scala:426)
	at kafka.log.Cleaner$$anonfun$clean$4.apply(LogCleaner.scala:363)
	at kafka.log.Cleaner$$anonfun$clean$4.apply(LogCleaner.scala:362)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at kafka.log.Cleaner.clean(LogCleaner.scala:362)
	at kafka.log.LogCleaner$CleanerThread.cleanOrSleep(LogCleaner.scala:241)
	at kafka.log.LogCleaner$CleanerThread.doWork(LogCleaner.scala:220)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:63)
Caused by: java.nio.file.FileSystemException: \tmp\kafka-logs\__consumer_offsets-46\00000000000000000000.log.cleaned -> \tmp\kafka-logs\__consumer_offsets-46\00000000000000000000.log.swap: El proceso no tiene acceso al archivo porque está siendo utilizado por otro proceso.

	at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:86)
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
	at sun.nio.fs.WindowsFileCopy.move(WindowsFileCopy.java:387)
	at sun.nio.fs.WindowsFileSystemProvider.move(WindowsFileSystemProvider.java:287)
	at java.nio.file.Files.move(Files.java:1395)
	at org.apache.kafka.common.utils.Utils.atomicMoveWithFallback(Utils.java:711)
	at org.apache.kafka.common.record.FileRecords.renameTo(FileRecords.java:210)
	... 10 more
	Suppressed: java.nio.file.FileSystemException: \tmp\kafka-logs\__consumer_offsets-46\00000000000000000000.log.cleaned -> \tmp\kafka-logs\__consumer_offsets-46\00000000000000000000.log.swap: El proceso no tiene acceso al archivo porque está siendo utilizado por otro proceso.

		at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:86)
		at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
		at sun.nio.fs.WindowsFileCopy.move(WindowsFileCopy.java:301)
		at sun.nio.fs.WindowsFileSystemProvider.move(WindowsFileSystemProvider.java:287)
		at java.nio.file.Files.move(Files.java:1395)
		at org.apache.kafka.common.utils.Utils.atomicMoveWithFallback(Utils.java:708)
		... 11 more
[2017-04-09 17:33:19,169] INFO [kafka-log-cleaner-thread-0], Stopped  (kafka.log.LogCleaner)
[2017-04-11 12:42:19,557] INFO Starting the log cleaner (kafka.log.LogCleaner)
[2017-04-11 12:42:19,561] INFO [kafka-log-cleaner-thread-0], Starting  (kafka.log.LogCleaner)
[2017-04-11 12:42:19,595] INFO Cleaner 0: Beginning cleaning of log __consumer_offsets-13. (kafka.log.LogCleaner)
[2017-04-11 12:42:19,595] INFO Cleaner 0: Building offset map for __consumer_offsets-13... (kafka.log.LogCleaner)
[2017-04-11 12:42:19,639] INFO Cleaner 0: Building offset map for log __consumer_offsets-13 for 1 segments in offset range [0, 15). (kafka.log.LogCleaner)
[2017-04-11 12:42:19,650] INFO Cleaner 0: Offset map for log __consumer_offsets-13 complete. (kafka.log.LogCleaner)
[2017-04-11 12:42:19,659] INFO Cleaner 0: Cleaning log __consumer_offsets-13 (cleaning prior to Mon Apr 03 20:09:00 CEST 2017, discarding tombstones prior to Thu Jan 01 01:00:00 CET 1970)... (kafka.log.LogCleaner)
[2017-04-11 12:42:19,665] INFO Cleaner 0: Cleaning segment 0 in log __consumer_offsets-13 (largest timestamp Mon Apr 03 20:09:00 CEST 2017) into 0, retaining deletes. (kafka.log.LogCleaner)
[2017-04-11 12:42:19,720] INFO Cleaner 0: Swapping in cleaned segment 0 for segment(s) 0 in log __consumer_offsets-13. (kafka.log.LogCleaner)
[2017-04-11 12:42:19,737] ERROR [kafka-log-cleaner-thread-0], Error due to  (kafka.log.LogCleaner)
kafka.common.KafkaStorageException: Failed to change the log file suffix from .cleaned to .swap for log segment 0
	at kafka.log.LogSegment.kafkaStorageException$1(LogSegment.scala:340)
	at kafka.log.LogSegment.changeFileSuffixes(LogSegment.scala:342)
	at kafka.log.Log.replaceSegments(Log.scala:1018)
	at kafka.log.Cleaner.cleanSegments(LogCleaner.scala:426)
	at kafka.log.Cleaner$$anonfun$clean$4.apply(LogCleaner.scala:363)
	at kafka.log.Cleaner$$anonfun$clean$4.apply(LogCleaner.scala:362)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at kafka.log.Cleaner.clean(LogCleaner.scala:362)
	at kafka.log.LogCleaner$CleanerThread.cleanOrSleep(LogCleaner.scala:241)
	at kafka.log.LogCleaner$CleanerThread.doWork(LogCleaner.scala:220)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:63)
Caused by: java.nio.file.FileSystemException: \tmp\kafka-logs\__consumer_offsets-13\00000000000000000000.log.cleaned -> \tmp\kafka-logs\__consumer_offsets-13\00000000000000000000.log.swap: El proceso no tiene acceso al archivo porque está siendo utilizado por otro proceso.

	at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:86)
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
	at sun.nio.fs.WindowsFileCopy.move(WindowsFileCopy.java:387)
	at sun.nio.fs.WindowsFileSystemProvider.move(WindowsFileSystemProvider.java:287)
	at java.nio.file.Files.move(Files.java:1395)
	at org.apache.kafka.common.utils.Utils.atomicMoveWithFallback(Utils.java:711)
	at org.apache.kafka.common.record.FileRecords.renameTo(FileRecords.java:210)
	... 10 more
	Suppressed: java.nio.file.FileSystemException: \tmp\kafka-logs\__consumer_offsets-13\00000000000000000000.log.cleaned -> \tmp\kafka-logs\__consumer_offsets-13\00000000000000000000.log.swap: El proceso no tiene acceso al archivo porque está siendo utilizado por otro proceso.

		at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:86)
		at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
		at sun.nio.fs.WindowsFileCopy.move(WindowsFileCopy.java:301)
		at sun.nio.fs.WindowsFileSystemProvider.move(WindowsFileSystemProvider.java:287)
		at java.nio.file.Files.move(Files.java:1395)
		at org.apache.kafka.common.utils.Utils.atomicMoveWithFallback(Utils.java:708)
		... 11 more
[2017-04-11 12:42:19,741] INFO [kafka-log-cleaner-thread-0], Stopped  (kafka.log.LogCleaner)
[2017-04-11 12:51:45,367] INFO Starting the log cleaner (kafka.log.LogCleaner)
[2017-04-11 12:51:45,368] INFO [kafka-log-cleaner-thread-0], Starting  (kafka.log.LogCleaner)
[2017-04-11 12:51:45,400] INFO Cleaner 0: Beginning cleaning of log __consumer_offsets-13. (kafka.log.LogCleaner)
[2017-04-11 12:51:45,401] INFO Cleaner 0: Building offset map for __consumer_offsets-13... (kafka.log.LogCleaner)
[2017-04-11 12:51:45,445] INFO Cleaner 0: Building offset map for log __consumer_offsets-13 for 1 segments in offset range [0, 15). (kafka.log.LogCleaner)
[2017-04-11 12:51:45,454] INFO Cleaner 0: Offset map for log __consumer_offsets-13 complete. (kafka.log.LogCleaner)
[2017-04-11 12:51:45,461] INFO Cleaner 0: Cleaning log __consumer_offsets-13 (cleaning prior to Mon Apr 03 20:09:00 CEST 2017, discarding tombstones prior to Thu Jan 01 01:00:00 CET 1970)... (kafka.log.LogCleaner)
[2017-04-11 12:51:45,466] INFO Cleaner 0: Cleaning segment 0 in log __consumer_offsets-13 (largest timestamp Mon Apr 03 20:09:00 CEST 2017) into 0, retaining deletes. (kafka.log.LogCleaner)
[2017-04-11 12:51:45,513] INFO Cleaner 0: Swapping in cleaned segment 0 for segment(s) 0 in log __consumer_offsets-13. (kafka.log.LogCleaner)
[2017-04-11 12:51:45,533] ERROR [kafka-log-cleaner-thread-0], Error due to  (kafka.log.LogCleaner)
kafka.common.KafkaStorageException: Failed to change the log file suffix from .cleaned to .swap for log segment 0
	at kafka.log.LogSegment.kafkaStorageException$1(LogSegment.scala:340)
	at kafka.log.LogSegment.changeFileSuffixes(LogSegment.scala:342)
	at kafka.log.Log.replaceSegments(Log.scala:1018)
	at kafka.log.Cleaner.cleanSegments(LogCleaner.scala:426)
	at kafka.log.Cleaner$$anonfun$clean$4.apply(LogCleaner.scala:363)
	at kafka.log.Cleaner$$anonfun$clean$4.apply(LogCleaner.scala:362)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at kafka.log.Cleaner.clean(LogCleaner.scala:362)
	at kafka.log.LogCleaner$CleanerThread.cleanOrSleep(LogCleaner.scala:241)
	at kafka.log.LogCleaner$CleanerThread.doWork(LogCleaner.scala:220)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:63)
Caused by: java.nio.file.FileSystemException: \tmp\kafka-logs\__consumer_offsets-13\00000000000000000000.log.cleaned -> \tmp\kafka-logs\__consumer_offsets-13\00000000000000000000.log.swap: El proceso no tiene acceso al archivo porque está siendo utilizado por otro proceso.

	at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:86)
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
	at sun.nio.fs.WindowsFileCopy.move(WindowsFileCopy.java:387)
	at sun.nio.fs.WindowsFileSystemProvider.move(WindowsFileSystemProvider.java:287)
	at java.nio.file.Files.move(Files.java:1395)
	at org.apache.kafka.common.utils.Utils.atomicMoveWithFallback(Utils.java:711)
	at org.apache.kafka.common.record.FileRecords.renameTo(FileRecords.java:210)
	... 10 more
	Suppressed: java.nio.file.FileSystemException: \tmp\kafka-logs\__consumer_offsets-13\00000000000000000000.log.cleaned -> \tmp\kafka-logs\__consumer_offsets-13\00000000000000000000.log.swap: El proceso no tiene acceso al archivo porque está siendo utilizado por otro proceso.

		at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:86)
		at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
		at sun.nio.fs.WindowsFileCopy.move(WindowsFileCopy.java:301)
		at sun.nio.fs.WindowsFileSystemProvider.move(WindowsFileSystemProvider.java:287)
		at java.nio.file.Files.move(Files.java:1395)
		at org.apache.kafka.common.utils.Utils.atomicMoveWithFallback(Utils.java:708)
		... 11 more
[2017-04-11 12:51:45,542] INFO [kafka-log-cleaner-thread-0], Stopped  (kafka.log.LogCleaner)
[2017-04-11 12:51:51,969] INFO Shutting down the log cleaner. (kafka.log.LogCleaner)
[2017-04-11 12:51:51,970] INFO [kafka-log-cleaner-thread-0], Shutting down (kafka.log.LogCleaner)
[2017-04-11 12:51:51,970] INFO [kafka-log-cleaner-thread-0], Shutdown completed (kafka.log.LogCleaner)
[2017-04-11 12:53:20,022] INFO Starting the log cleaner (kafka.log.LogCleaner)
[2017-04-11 12:53:20,024] INFO [kafka-log-cleaner-thread-0], Starting  (kafka.log.LogCleaner)
[2017-04-11 12:53:20,045] INFO Cleaner 0: Beginning cleaning of log __consumer_offsets-13. (kafka.log.LogCleaner)
[2017-04-11 12:53:20,045] INFO Cleaner 0: Building offset map for __consumer_offsets-13... (kafka.log.LogCleaner)
[2017-04-11 12:53:20,086] INFO Cleaner 0: Building offset map for log __consumer_offsets-13 for 1 segments in offset range [0, 15). (kafka.log.LogCleaner)
[2017-04-11 12:53:20,097] INFO Cleaner 0: Offset map for log __consumer_offsets-13 complete. (kafka.log.LogCleaner)
[2017-04-11 12:53:20,101] INFO Cleaner 0: Cleaning log __consumer_offsets-13 (cleaning prior to Mon Apr 03 20:09:00 CEST 2017, discarding tombstones prior to Thu Jan 01 01:00:00 CET 1970)... (kafka.log.LogCleaner)
[2017-04-11 12:53:20,107] INFO Cleaner 0: Cleaning segment 0 in log __consumer_offsets-13 (largest timestamp Mon Apr 03 20:09:00 CEST 2017) into 0, retaining deletes. (kafka.log.LogCleaner)
[2017-04-11 12:53:20,145] INFO Cleaner 0: Swapping in cleaned segment 0 for segment(s) 0 in log __consumer_offsets-13. (kafka.log.LogCleaner)
[2017-04-11 12:53:20,159] ERROR [kafka-log-cleaner-thread-0], Error due to  (kafka.log.LogCleaner)
kafka.common.KafkaStorageException: Failed to change the log file suffix from .cleaned to .swap for log segment 0
	at kafka.log.LogSegment.kafkaStorageException$1(LogSegment.scala:340)
	at kafka.log.LogSegment.changeFileSuffixes(LogSegment.scala:342)
	at kafka.log.Log.replaceSegments(Log.scala:1018)
	at kafka.log.Cleaner.cleanSegments(LogCleaner.scala:426)
	at kafka.log.Cleaner$$anonfun$clean$4.apply(LogCleaner.scala:363)
	at kafka.log.Cleaner$$anonfun$clean$4.apply(LogCleaner.scala:362)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at kafka.log.Cleaner.clean(LogCleaner.scala:362)
	at kafka.log.LogCleaner$CleanerThread.cleanOrSleep(LogCleaner.scala:241)
	at kafka.log.LogCleaner$CleanerThread.doWork(LogCleaner.scala:220)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:63)
Caused by: java.nio.file.FileSystemException: \tmp\kafka-logs\__consumer_offsets-13\00000000000000000000.log.cleaned -> \tmp\kafka-logs\__consumer_offsets-13\00000000000000000000.log.swap: El proceso no tiene acceso al archivo porque está siendo utilizado por otro proceso.

	at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:86)
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
	at sun.nio.fs.WindowsFileCopy.move(WindowsFileCopy.java:387)
	at sun.nio.fs.WindowsFileSystemProvider.move(WindowsFileSystemProvider.java:287)
	at java.nio.file.Files.move(Files.java:1395)
	at org.apache.kafka.common.utils.Utils.atomicMoveWithFallback(Utils.java:711)
	at org.apache.kafka.common.record.FileRecords.renameTo(FileRecords.java:210)
	... 10 more
	Suppressed: java.nio.file.FileSystemException: \tmp\kafka-logs\__consumer_offsets-13\00000000000000000000.log.cleaned -> \tmp\kafka-logs\__consumer_offsets-13\00000000000000000000.log.swap: El proceso no tiene acceso al archivo porque está siendo utilizado por otro proceso.

		at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:86)
		at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
		at sun.nio.fs.WindowsFileCopy.move(WindowsFileCopy.java:301)
		at sun.nio.fs.WindowsFileSystemProvider.move(WindowsFileSystemProvider.java:287)
		at java.nio.file.Files.move(Files.java:1395)
		at org.apache.kafka.common.utils.Utils.atomicMoveWithFallback(Utils.java:708)
		... 11 more
[2017-04-11 12:53:20,163] INFO [kafka-log-cleaner-thread-0], Stopped  (kafka.log.LogCleaner)
[2017-04-11 12:59:33,859] INFO Starting the log cleaner (kafka.log.LogCleaner)
[2017-04-11 12:59:33,861] INFO [kafka-log-cleaner-thread-0], Starting  (kafka.log.LogCleaner)
[2017-04-11 12:59:33,904] INFO Cleaner 0: Beginning cleaning of log __consumer_offsets-13. (kafka.log.LogCleaner)
[2017-04-11 12:59:33,904] INFO Cleaner 0: Building offset map for __consumer_offsets-13... (kafka.log.LogCleaner)
[2017-04-11 12:59:33,948] INFO Cleaner 0: Building offset map for log __consumer_offsets-13 for 1 segments in offset range [0, 15). (kafka.log.LogCleaner)
[2017-04-11 12:59:33,957] INFO Cleaner 0: Offset map for log __consumer_offsets-13 complete. (kafka.log.LogCleaner)
[2017-04-11 12:59:33,963] INFO Cleaner 0: Cleaning log __consumer_offsets-13 (cleaning prior to Mon Apr 03 20:09:00 CEST 2017, discarding tombstones prior to Thu Jan 01 01:00:00 CET 1970)... (kafka.log.LogCleaner)
[2017-04-11 12:59:33,968] INFO Cleaner 0: Cleaning segment 0 in log __consumer_offsets-13 (largest timestamp Mon Apr 03 20:09:00 CEST 2017) into 0, retaining deletes. (kafka.log.LogCleaner)
[2017-04-11 12:59:34,010] INFO Cleaner 0: Swapping in cleaned segment 0 for segment(s) 0 in log __consumer_offsets-13. (kafka.log.LogCleaner)
[2017-04-11 12:59:34,030] ERROR [kafka-log-cleaner-thread-0], Error due to  (kafka.log.LogCleaner)
kafka.common.KafkaStorageException: Failed to change the log file suffix from .cleaned to .swap for log segment 0
	at kafka.log.LogSegment.kafkaStorageException$1(LogSegment.scala:340)
	at kafka.log.LogSegment.changeFileSuffixes(LogSegment.scala:342)
	at kafka.log.Log.replaceSegments(Log.scala:1018)
	at kafka.log.Cleaner.cleanSegments(LogCleaner.scala:426)
	at kafka.log.Cleaner$$anonfun$clean$4.apply(LogCleaner.scala:363)
	at kafka.log.Cleaner$$anonfun$clean$4.apply(LogCleaner.scala:362)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at kafka.log.Cleaner.clean(LogCleaner.scala:362)
	at kafka.log.LogCleaner$CleanerThread.cleanOrSleep(LogCleaner.scala:241)
	at kafka.log.LogCleaner$CleanerThread.doWork(LogCleaner.scala:220)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:63)
Caused by: java.nio.file.FileSystemException: \tmp\kafka-logs\__consumer_offsets-13\00000000000000000000.log.cleaned -> \tmp\kafka-logs\__consumer_offsets-13\00000000000000000000.log.swap: El proceso no tiene acceso al archivo porque está siendo utilizado por otro proceso.

	at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:86)
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
	at sun.nio.fs.WindowsFileCopy.move(WindowsFileCopy.java:387)
	at sun.nio.fs.WindowsFileSystemProvider.move(WindowsFileSystemProvider.java:287)
	at java.nio.file.Files.move(Files.java:1395)
	at org.apache.kafka.common.utils.Utils.atomicMoveWithFallback(Utils.java:711)
	at org.apache.kafka.common.record.FileRecords.renameTo(FileRecords.java:210)
	... 10 more
	Suppressed: java.nio.file.FileSystemException: \tmp\kafka-logs\__consumer_offsets-13\00000000000000000000.log.cleaned -> \tmp\kafka-logs\__consumer_offsets-13\00000000000000000000.log.swap: El proceso no tiene acceso al archivo porque está siendo utilizado por otro proceso.

		at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:86)
		at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
		at sun.nio.fs.WindowsFileCopy.move(WindowsFileCopy.java:301)
		at sun.nio.fs.WindowsFileSystemProvider.move(WindowsFileSystemProvider.java:287)
		at java.nio.file.Files.move(Files.java:1395)
		at org.apache.kafka.common.utils.Utils.atomicMoveWithFallback(Utils.java:708)
		... 11 more
[2017-04-11 12:59:34,037] INFO [kafka-log-cleaner-thread-0], Stopped  (kafka.log.LogCleaner)
[2017-04-11 12:59:40,454] INFO Shutting down the log cleaner. (kafka.log.LogCleaner)
[2017-04-11 12:59:40,455] INFO [kafka-log-cleaner-thread-0], Shutting down (kafka.log.LogCleaner)
[2017-04-11 12:59:40,455] INFO [kafka-log-cleaner-thread-0], Shutdown completed (kafka.log.LogCleaner)
[2017-04-11 13:00:49,545] INFO Starting the log cleaner (kafka.log.LogCleaner)
[2017-04-11 13:00:49,547] INFO [kafka-log-cleaner-thread-0], Starting  (kafka.log.LogCleaner)
[2017-04-11 13:00:49,571] INFO Cleaner 0: Beginning cleaning of log __consumer_offsets-13. (kafka.log.LogCleaner)
[2017-04-11 13:00:49,571] INFO Cleaner 0: Building offset map for __consumer_offsets-13... (kafka.log.LogCleaner)
[2017-04-11 13:00:49,611] INFO Cleaner 0: Building offset map for log __consumer_offsets-13 for 1 segments in offset range [0, 15). (kafka.log.LogCleaner)
[2017-04-11 13:00:49,623] INFO Cleaner 0: Offset map for log __consumer_offsets-13 complete. (kafka.log.LogCleaner)
[2017-04-11 13:00:49,628] INFO Cleaner 0: Cleaning log __consumer_offsets-13 (cleaning prior to Mon Apr 03 20:09:00 CEST 2017, discarding tombstones prior to Thu Jan 01 01:00:00 CET 1970)... (kafka.log.LogCleaner)
[2017-04-11 13:00:49,634] INFO Cleaner 0: Cleaning segment 0 in log __consumer_offsets-13 (largest timestamp Mon Apr 03 20:09:00 CEST 2017) into 0, retaining deletes. (kafka.log.LogCleaner)
[2017-04-11 13:00:49,673] INFO Cleaner 0: Swapping in cleaned segment 0 for segment(s) 0 in log __consumer_offsets-13. (kafka.log.LogCleaner)
[2017-04-11 13:00:49,689] ERROR [kafka-log-cleaner-thread-0], Error due to  (kafka.log.LogCleaner)
kafka.common.KafkaStorageException: Failed to change the log file suffix from .cleaned to .swap for log segment 0
	at kafka.log.LogSegment.kafkaStorageException$1(LogSegment.scala:340)
	at kafka.log.LogSegment.changeFileSuffixes(LogSegment.scala:342)
	at kafka.log.Log.replaceSegments(Log.scala:1018)
	at kafka.log.Cleaner.cleanSegments(LogCleaner.scala:426)
	at kafka.log.Cleaner$$anonfun$clean$4.apply(LogCleaner.scala:363)
	at kafka.log.Cleaner$$anonfun$clean$4.apply(LogCleaner.scala:362)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at kafka.log.Cleaner.clean(LogCleaner.scala:362)
	at kafka.log.LogCleaner$CleanerThread.cleanOrSleep(LogCleaner.scala:241)
	at kafka.log.LogCleaner$CleanerThread.doWork(LogCleaner.scala:220)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:63)
Caused by: java.nio.file.FileSystemException: \tmp\kafka-logs\__consumer_offsets-13\00000000000000000000.log.cleaned -> \tmp\kafka-logs\__consumer_offsets-13\00000000000000000000.log.swap: El proceso no tiene acceso al archivo porque está siendo utilizado por otro proceso.

	at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:86)
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
	at sun.nio.fs.WindowsFileCopy.move(WindowsFileCopy.java:387)
	at sun.nio.fs.WindowsFileSystemProvider.move(WindowsFileSystemProvider.java:287)
	at java.nio.file.Files.move(Files.java:1395)
	at org.apache.kafka.common.utils.Utils.atomicMoveWithFallback(Utils.java:711)
	at org.apache.kafka.common.record.FileRecords.renameTo(FileRecords.java:210)
	... 10 more
	Suppressed: java.nio.file.FileSystemException: \tmp\kafka-logs\__consumer_offsets-13\00000000000000000000.log.cleaned -> \tmp\kafka-logs\__consumer_offsets-13\00000000000000000000.log.swap: El proceso no tiene acceso al archivo porque está siendo utilizado por otro proceso.

		at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:86)
		at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
		at sun.nio.fs.WindowsFileCopy.move(WindowsFileCopy.java:301)
		at sun.nio.fs.WindowsFileSystemProvider.move(WindowsFileSystemProvider.java:287)
		at java.nio.file.Files.move(Files.java:1395)
		at org.apache.kafka.common.utils.Utils.atomicMoveWithFallback(Utils.java:708)
		... 11 more
[2017-04-11 13:00:49,692] INFO [kafka-log-cleaner-thread-0], Stopped  (kafka.log.LogCleaner)
[2017-04-11 13:28:00,236] INFO Starting the log cleaner (kafka.log.LogCleaner)
[2017-04-11 13:28:00,238] INFO [kafka-log-cleaner-thread-0], Starting  (kafka.log.LogCleaner)
[2017-04-11 13:28:00,262] INFO Cleaner 0: Beginning cleaning of log __consumer_offsets-13. (kafka.log.LogCleaner)
[2017-04-11 13:28:00,262] INFO Cleaner 0: Building offset map for __consumer_offsets-13... (kafka.log.LogCleaner)
[2017-04-11 13:28:00,303] INFO Cleaner 0: Building offset map for log __consumer_offsets-13 for 1 segments in offset range [0, 15). (kafka.log.LogCleaner)
[2017-04-11 13:28:00,313] INFO Cleaner 0: Offset map for log __consumer_offsets-13 complete. (kafka.log.LogCleaner)
[2017-04-11 13:28:00,321] INFO Cleaner 0: Cleaning log __consumer_offsets-13 (cleaning prior to Mon Apr 03 20:09:00 CEST 2017, discarding tombstones prior to Thu Jan 01 01:00:00 CET 1970)... (kafka.log.LogCleaner)
[2017-04-11 13:28:00,332] INFO Cleaner 0: Cleaning segment 0 in log __consumer_offsets-13 (largest timestamp Mon Apr 03 20:09:00 CEST 2017) into 0, retaining deletes. (kafka.log.LogCleaner)
[2017-04-11 13:28:00,383] INFO Cleaner 0: Swapping in cleaned segment 0 for segment(s) 0 in log __consumer_offsets-13. (kafka.log.LogCleaner)
[2017-04-11 13:28:00,411] ERROR [kafka-log-cleaner-thread-0], Error due to  (kafka.log.LogCleaner)
kafka.common.KafkaStorageException: Failed to change the log file suffix from .cleaned to .swap for log segment 0
	at kafka.log.LogSegment.kafkaStorageException$1(LogSegment.scala:340)
	at kafka.log.LogSegment.changeFileSuffixes(LogSegment.scala:342)
	at kafka.log.Log.replaceSegments(Log.scala:1018)
	at kafka.log.Cleaner.cleanSegments(LogCleaner.scala:426)
	at kafka.log.Cleaner$$anonfun$clean$4.apply(LogCleaner.scala:363)
	at kafka.log.Cleaner$$anonfun$clean$4.apply(LogCleaner.scala:362)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at kafka.log.Cleaner.clean(LogCleaner.scala:362)
	at kafka.log.LogCleaner$CleanerThread.cleanOrSleep(LogCleaner.scala:241)
	at kafka.log.LogCleaner$CleanerThread.doWork(LogCleaner.scala:220)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:63)
Caused by: java.nio.file.FileSystemException: \tmp\kafka-logs\__consumer_offsets-13\00000000000000000000.log.cleaned -> \tmp\kafka-logs\__consumer_offsets-13\00000000000000000000.log.swap: El proceso no tiene acceso al archivo porque está siendo utilizado por otro proceso.

	at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:86)
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
	at sun.nio.fs.WindowsFileCopy.move(WindowsFileCopy.java:387)
	at sun.nio.fs.WindowsFileSystemProvider.move(WindowsFileSystemProvider.java:287)
	at java.nio.file.Files.move(Files.java:1395)
	at org.apache.kafka.common.utils.Utils.atomicMoveWithFallback(Utils.java:711)
	at org.apache.kafka.common.record.FileRecords.renameTo(FileRecords.java:210)
	... 10 more
	Suppressed: java.nio.file.FileSystemException: \tmp\kafka-logs\__consumer_offsets-13\00000000000000000000.log.cleaned -> \tmp\kafka-logs\__consumer_offsets-13\00000000000000000000.log.swap: El proceso no tiene acceso al archivo porque está siendo utilizado por otro proceso.

		at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:86)
		at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
		at sun.nio.fs.WindowsFileCopy.move(WindowsFileCopy.java:301)
		at sun.nio.fs.WindowsFileSystemProvider.move(WindowsFileSystemProvider.java:287)
		at java.nio.file.Files.move(Files.java:1395)
		at org.apache.kafka.common.utils.Utils.atomicMoveWithFallback(Utils.java:708)
		... 11 more
[2017-04-11 13:28:00,435] INFO [kafka-log-cleaner-thread-0], Stopped  (kafka.log.LogCleaner)
[2017-04-11 15:34:58,798] INFO Starting the log cleaner (kafka.log.LogCleaner)
[2017-04-11 15:34:58,801] INFO [kafka-log-cleaner-thread-0], Starting  (kafka.log.LogCleaner)
[2017-04-11 15:34:58,829] INFO Cleaner 0: Beginning cleaning of log __consumer_offsets-13. (kafka.log.LogCleaner)
[2017-04-11 15:34:58,829] INFO Cleaner 0: Building offset map for __consumer_offsets-13... (kafka.log.LogCleaner)
[2017-04-11 15:34:58,869] INFO Cleaner 0: Building offset map for log __consumer_offsets-13 for 1 segments in offset range [0, 15). (kafka.log.LogCleaner)
[2017-04-11 15:34:58,880] INFO Cleaner 0: Offset map for log __consumer_offsets-13 complete. (kafka.log.LogCleaner)
[2017-04-11 15:34:58,886] INFO Cleaner 0: Cleaning log __consumer_offsets-13 (cleaning prior to Mon Apr 03 20:09:00 CEST 2017, discarding tombstones prior to Thu Jan 01 01:00:00 CET 1970)... (kafka.log.LogCleaner)
[2017-04-11 15:34:58,890] INFO Cleaner 0: Cleaning segment 0 in log __consumer_offsets-13 (largest timestamp Mon Apr 03 20:09:00 CEST 2017) into 0, retaining deletes. (kafka.log.LogCleaner)
[2017-04-11 15:34:58,953] INFO Cleaner 0: Swapping in cleaned segment 0 for segment(s) 0 in log __consumer_offsets-13. (kafka.log.LogCleaner)
[2017-04-11 15:34:59,003] ERROR [kafka-log-cleaner-thread-0], Error due to  (kafka.log.LogCleaner)
kafka.common.KafkaStorageException: Failed to change the log file suffix from .cleaned to .swap for log segment 0
	at kafka.log.LogSegment.kafkaStorageException$1(LogSegment.scala:340)
	at kafka.log.LogSegment.changeFileSuffixes(LogSegment.scala:342)
	at kafka.log.Log.replaceSegments(Log.scala:1018)
	at kafka.log.Cleaner.cleanSegments(LogCleaner.scala:426)
	at kafka.log.Cleaner$$anonfun$clean$4.apply(LogCleaner.scala:363)
	at kafka.log.Cleaner$$anonfun$clean$4.apply(LogCleaner.scala:362)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at kafka.log.Cleaner.clean(LogCleaner.scala:362)
	at kafka.log.LogCleaner$CleanerThread.cleanOrSleep(LogCleaner.scala:241)
	at kafka.log.LogCleaner$CleanerThread.doWork(LogCleaner.scala:220)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:63)
Caused by: java.nio.file.FileSystemException: \tmp\kafka-logs\__consumer_offsets-13\00000000000000000000.log.cleaned -> \tmp\kafka-logs\__consumer_offsets-13\00000000000000000000.log.swap: El proceso no tiene acceso al archivo porque está siendo utilizado por otro proceso.

	at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:86)
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
	at sun.nio.fs.WindowsFileCopy.move(WindowsFileCopy.java:387)
	at sun.nio.fs.WindowsFileSystemProvider.move(WindowsFileSystemProvider.java:287)
	at java.nio.file.Files.move(Files.java:1395)
	at org.apache.kafka.common.utils.Utils.atomicMoveWithFallback(Utils.java:711)
	at org.apache.kafka.common.record.FileRecords.renameTo(FileRecords.java:210)
	... 10 more
	Suppressed: java.nio.file.FileSystemException: \tmp\kafka-logs\__consumer_offsets-13\00000000000000000000.log.cleaned -> \tmp\kafka-logs\__consumer_offsets-13\00000000000000000000.log.swap: El proceso no tiene acceso al archivo porque está siendo utilizado por otro proceso.

		at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:86)
		at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
		at sun.nio.fs.WindowsFileCopy.move(WindowsFileCopy.java:301)
		at sun.nio.fs.WindowsFileSystemProvider.move(WindowsFileSystemProvider.java:287)
		at java.nio.file.Files.move(Files.java:1395)
		at org.apache.kafka.common.utils.Utils.atomicMoveWithFallback(Utils.java:708)
		... 11 more
[2017-04-11 15:34:59,008] INFO [kafka-log-cleaner-thread-0], Stopped  (kafka.log.LogCleaner)
[2017-04-11 15:47:30,036] INFO Starting the log cleaner (kafka.log.LogCleaner)
[2017-04-11 15:47:30,038] INFO [kafka-log-cleaner-thread-0], Starting  (kafka.log.LogCleaner)
[2017-04-11 15:47:30,065] INFO Cleaner 0: Beginning cleaning of log __consumer_offsets-13. (kafka.log.LogCleaner)
[2017-04-11 15:47:30,066] INFO Cleaner 0: Building offset map for __consumer_offsets-13... (kafka.log.LogCleaner)
[2017-04-11 15:47:30,105] INFO Cleaner 0: Building offset map for log __consumer_offsets-13 for 1 segments in offset range [0, 15). (kafka.log.LogCleaner)
[2017-04-11 15:47:30,115] INFO Cleaner 0: Offset map for log __consumer_offsets-13 complete. (kafka.log.LogCleaner)
[2017-04-11 15:47:30,120] INFO Cleaner 0: Cleaning log __consumer_offsets-13 (cleaning prior to Mon Apr 03 20:09:00 CEST 2017, discarding tombstones prior to Thu Jan 01 01:00:00 CET 1970)... (kafka.log.LogCleaner)
[2017-04-11 15:47:30,126] INFO Cleaner 0: Cleaning segment 0 in log __consumer_offsets-13 (largest timestamp Mon Apr 03 20:09:00 CEST 2017) into 0, retaining deletes. (kafka.log.LogCleaner)
[2017-04-11 15:47:30,163] INFO Cleaner 0: Swapping in cleaned segment 0 for segment(s) 0 in log __consumer_offsets-13. (kafka.log.LogCleaner)
[2017-04-11 15:47:30,183] ERROR [kafka-log-cleaner-thread-0], Error due to  (kafka.log.LogCleaner)
kafka.common.KafkaStorageException: Failed to change the log file suffix from .cleaned to .swap for log segment 0
	at kafka.log.LogSegment.kafkaStorageException$1(LogSegment.scala:340)
	at kafka.log.LogSegment.changeFileSuffixes(LogSegment.scala:342)
	at kafka.log.Log.replaceSegments(Log.scala:1018)
	at kafka.log.Cleaner.cleanSegments(LogCleaner.scala:426)
	at kafka.log.Cleaner$$anonfun$clean$4.apply(LogCleaner.scala:363)
	at kafka.log.Cleaner$$anonfun$clean$4.apply(LogCleaner.scala:362)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at kafka.log.Cleaner.clean(LogCleaner.scala:362)
	at kafka.log.LogCleaner$CleanerThread.cleanOrSleep(LogCleaner.scala:241)
	at kafka.log.LogCleaner$CleanerThread.doWork(LogCleaner.scala:220)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:63)
Caused by: java.nio.file.FileSystemException: \tmp\kafka-logs\__consumer_offsets-13\00000000000000000000.log.cleaned -> \tmp\kafka-logs\__consumer_offsets-13\00000000000000000000.log.swap: El proceso no tiene acceso al archivo porque está siendo utilizado por otro proceso.

	at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:86)
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
	at sun.nio.fs.WindowsFileCopy.move(WindowsFileCopy.java:387)
	at sun.nio.fs.WindowsFileSystemProvider.move(WindowsFileSystemProvider.java:287)
	at java.nio.file.Files.move(Files.java:1395)
	at org.apache.kafka.common.utils.Utils.atomicMoveWithFallback(Utils.java:711)
	at org.apache.kafka.common.record.FileRecords.renameTo(FileRecords.java:210)
	... 10 more
	Suppressed: java.nio.file.FileSystemException: \tmp\kafka-logs\__consumer_offsets-13\00000000000000000000.log.cleaned -> \tmp\kafka-logs\__consumer_offsets-13\00000000000000000000.log.swap: El proceso no tiene acceso al archivo porque está siendo utilizado por otro proceso.

		at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:86)
		at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
		at sun.nio.fs.WindowsFileCopy.move(WindowsFileCopy.java:301)
		at sun.nio.fs.WindowsFileSystemProvider.move(WindowsFileSystemProvider.java:287)
		at java.nio.file.Files.move(Files.java:1395)
		at org.apache.kafka.common.utils.Utils.atomicMoveWithFallback(Utils.java:708)
		... 11 more
[2017-04-11 15:47:30,190] INFO [kafka-log-cleaner-thread-0], Stopped  (kafka.log.LogCleaner)
[2017-04-13 19:01:08,658] INFO Starting the log cleaner (kafka.log.LogCleaner)
[2017-04-13 19:01:08,661] INFO [kafka-log-cleaner-thread-0], Starting  (kafka.log.LogCleaner)
